// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/notification/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/notification/service.go -destination=internal/core/notification/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/octobud-hq/octobud/backend/internal/db"
	models "github.com/octobud-hq/octobud/backend/internal/models"
	eval "github.com/octobud-hq/octobud/backend/internal/query/eval"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationReader is a mock of NotificationReader interface.
type MockNotificationReader struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationReaderMockRecorder
	isgomock struct{}
}

// MockNotificationReaderMockRecorder is the mock recorder for MockNotificationReader.
type MockNotificationReaderMockRecorder struct {
	mock *MockNotificationReader
}

// NewMockNotificationReader creates a new mock instance.
func NewMockNotificationReader(ctrl *gomock.Controller) *MockNotificationReader {
	mock := &MockNotificationReader{ctrl: ctrl}
	mock.recorder = &MockNotificationReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationReader) EXPECT() *MockNotificationReaderMockRecorder {
	return m.recorder
}

// BuildResponse mocks base method.
func (m *MockNotificationReader) BuildResponse(ctx context.Context, userID string, notification db.Notification, repoMap map[int64]db.Repository, evaluator *eval.Evaluator) (models.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildResponse", ctx, userID, notification, repoMap, evaluator)
	ret0, _ := ret[0].(models.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildResponse indicates an expected call of BuildResponse.
func (mr *MockNotificationReaderMockRecorder) BuildResponse(ctx, userID, notification, repoMap, evaluator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildResponse", reflect.TypeOf((*MockNotificationReader)(nil).BuildResponse), ctx, userID, notification, repoMap, evaluator)
}

// GetByGithubID mocks base method.
func (m *MockNotificationReader) GetByGithubID(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGithubID", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGithubID indicates an expected call of GetByGithubID.
func (mr *MockNotificationReaderMockRecorder) GetByGithubID(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGithubID", reflect.TypeOf((*MockNotificationReader)(nil).GetByGithubID), ctx, userID, githubID)
}

// GetNotificationWithDetails mocks base method.
func (m *MockNotificationReader) GetNotificationWithDetails(ctx context.Context, userID, githubID, queryStr string) (models.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationWithDetails", ctx, userID, githubID, queryStr)
	ret0, _ := ret[0].(models.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationWithDetails indicates an expected call of GetNotificationWithDetails.
func (mr *MockNotificationReaderMockRecorder) GetNotificationWithDetails(ctx, userID, githubID, queryStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationWithDetails", reflect.TypeOf((*MockNotificationReader)(nil).GetNotificationWithDetails), ctx, userID, githubID, queryStr)
}

// GetTagsForNotification mocks base method.
func (m *MockNotificationReader) GetTagsForNotification(ctx context.Context, userID string, notificationID int64) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsForNotification", ctx, userID, notificationID)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsForNotification indicates an expected call of GetTagsForNotification.
func (mr *MockNotificationReaderMockRecorder) GetTagsForNotification(ctx, userID, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsForNotification", reflect.TypeOf((*MockNotificationReader)(nil).GetTagsForNotification), ctx, userID, notificationID)
}

// IndexRepositories mocks base method.
func (m *MockNotificationReader) IndexRepositories(ctx context.Context, userID string) (map[int64]db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexRepositories", ctx, userID)
	ret0, _ := ret[0].(map[int64]db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexRepositories indicates an expected call of IndexRepositories.
func (mr *MockNotificationReaderMockRecorder) IndexRepositories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexRepositories", reflect.TypeOf((*MockNotificationReader)(nil).IndexRepositories), ctx, userID)
}

// ListNotifications mocks base method.
func (m *MockNotificationReader) ListNotifications(ctx context.Context, userID string, opts models.ListOptions) (models.ListDetailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, userID, opts)
	ret0, _ := ret[0].(models.ListDetailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockNotificationReaderMockRecorder) ListNotifications(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockNotificationReader)(nil).ListNotifications), ctx, userID, opts)
}

// ListNotificationsFromQueryString mocks base method.
func (m *MockNotificationReader) ListNotificationsFromQueryString(ctx context.Context, userID, queryStr string, limit int32) ([]db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationsFromQueryString", ctx, userID, queryStr, limit)
	ret0, _ := ret[0].([]db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationsFromQueryString indicates an expected call of ListNotificationsFromQueryString.
func (mr *MockNotificationReaderMockRecorder) ListNotificationsFromQueryString(ctx, userID, queryStr, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationsFromQueryString", reflect.TypeOf((*MockNotificationReader)(nil).ListNotificationsFromQueryString), ctx, userID, queryStr, limit)
}

// ListPollNotifications mocks base method.
func (m *MockNotificationReader) ListPollNotifications(ctx context.Context, userID string, opts models.ListOptions) (models.ListPollResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPollNotifications", ctx, userID, opts)
	ret0, _ := ret[0].(models.ListPollResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPollNotifications indicates an expected call of ListPollNotifications.
func (mr *MockNotificationReaderMockRecorder) ListPollNotifications(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPollNotifications", reflect.TypeOf((*MockNotificationReader)(nil).ListPollNotifications), ctx, userID, opts)
}

// NewEvaluator mocks base method.
func (m *MockNotificationReader) NewEvaluator(queryStr string) (*eval.Evaluator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEvaluator", queryStr)
	ret0, _ := ret[0].(*eval.Evaluator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewEvaluator indicates an expected call of NewEvaluator.
func (mr *MockNotificationReaderMockRecorder) NewEvaluator(queryStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEvaluator", reflect.TypeOf((*MockNotificationReader)(nil).NewEvaluator), queryStr)
}

// MockNotificationWriter is a mock of NotificationWriter interface.
type MockNotificationWriter struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationWriterMockRecorder
	isgomock struct{}
}

// MockNotificationWriterMockRecorder is the mock recorder for MockNotificationWriter.
type MockNotificationWriterMockRecorder struct {
	mock *MockNotificationWriter
}

// NewMockNotificationWriter creates a new mock instance.
func NewMockNotificationWriter(ctrl *gomock.Controller) *MockNotificationWriter {
	mock := &MockNotificationWriter{ctrl: ctrl}
	mock.recorder = &MockNotificationWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationWriter) EXPECT() *MockNotificationWriterMockRecorder {
	return m.recorder
}

// ArchiveNotification mocks base method.
func (m *MockNotificationWriter) ArchiveNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveNotification indicates an expected call of ArchiveNotification.
func (mr *MockNotificationWriterMockRecorder) ArchiveNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveNotification", reflect.TypeOf((*MockNotificationWriter)(nil).ArchiveNotification), ctx, userID, githubID)
}

// MarkNotificationRead mocks base method.
func (m *MockNotificationWriter) MarkNotificationRead(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationRead", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationRead indicates an expected call of MarkNotificationRead.
func (mr *MockNotificationWriterMockRecorder) MarkNotificationRead(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationRead", reflect.TypeOf((*MockNotificationWriter)(nil).MarkNotificationRead), ctx, userID, githubID)
}

// MarkNotificationUnread mocks base method.
func (m *MockNotificationWriter) MarkNotificationUnread(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationUnread", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationUnread indicates an expected call of MarkNotificationUnread.
func (mr *MockNotificationWriterMockRecorder) MarkNotificationUnread(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationUnread", reflect.TypeOf((*MockNotificationWriter)(nil).MarkNotificationUnread), ctx, userID, githubID)
}

// MuteNotification mocks base method.
func (m *MockNotificationWriter) MuteNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MuteNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MuteNotification indicates an expected call of MuteNotification.
func (mr *MockNotificationWriterMockRecorder) MuteNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MuteNotification", reflect.TypeOf((*MockNotificationWriter)(nil).MuteNotification), ctx, userID, githubID)
}

// SnoozeNotification mocks base method.
func (m *MockNotificationWriter) SnoozeNotification(ctx context.Context, userID, githubID, snoozedUntil string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnoozeNotification", ctx, userID, githubID, snoozedUntil)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnoozeNotification indicates an expected call of SnoozeNotification.
func (mr *MockNotificationWriterMockRecorder) SnoozeNotification(ctx, userID, githubID, snoozedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnoozeNotification", reflect.TypeOf((*MockNotificationWriter)(nil).SnoozeNotification), ctx, userID, githubID, snoozedUntil)
}

// StarNotification mocks base method.
func (m *MockNotificationWriter) StarNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StarNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StarNotification indicates an expected call of StarNotification.
func (mr *MockNotificationWriterMockRecorder) StarNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StarNotification", reflect.TypeOf((*MockNotificationWriter)(nil).StarNotification), ctx, userID, githubID)
}

// UnarchiveNotification mocks base method.
func (m *MockNotificationWriter) UnarchiveNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnarchiveNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnarchiveNotification indicates an expected call of UnarchiveNotification.
func (mr *MockNotificationWriterMockRecorder) UnarchiveNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnarchiveNotification", reflect.TypeOf((*MockNotificationWriter)(nil).UnarchiveNotification), ctx, userID, githubID)
}

// UnfilterNotification mocks base method.
func (m *MockNotificationWriter) UnfilterNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfilterNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnfilterNotification indicates an expected call of UnfilterNotification.
func (mr *MockNotificationWriterMockRecorder) UnfilterNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfilterNotification", reflect.TypeOf((*MockNotificationWriter)(nil).UnfilterNotification), ctx, userID, githubID)
}

// UnmuteNotification mocks base method.
func (m *MockNotificationWriter) UnmuteNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmuteNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmuteNotification indicates an expected call of UnmuteNotification.
func (mr *MockNotificationWriterMockRecorder) UnmuteNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmuteNotification", reflect.TypeOf((*MockNotificationWriter)(nil).UnmuteNotification), ctx, userID, githubID)
}

// UnsnoozeNotification mocks base method.
func (m *MockNotificationWriter) UnsnoozeNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsnoozeNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsnoozeNotification indicates an expected call of UnsnoozeNotification.
func (mr *MockNotificationWriterMockRecorder) UnsnoozeNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsnoozeNotification", reflect.TypeOf((*MockNotificationWriter)(nil).UnsnoozeNotification), ctx, userID, githubID)
}

// UnstarNotification mocks base method.
func (m *MockNotificationWriter) UnstarNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnstarNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnstarNotification indicates an expected call of UnstarNotification.
func (mr *MockNotificationWriterMockRecorder) UnstarNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnstarNotification", reflect.TypeOf((*MockNotificationWriter)(nil).UnstarNotification), ctx, userID, githubID)
}

// UpdateNotificationSubject mocks base method.
func (m *MockNotificationWriter) UpdateNotificationSubject(ctx context.Context, userID string, params db.UpdateNotificationSubjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationSubject", ctx, userID, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationSubject indicates an expected call of UpdateNotificationSubject.
func (mr *MockNotificationWriterMockRecorder) UpdateNotificationSubject(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationSubject", reflect.TypeOf((*MockNotificationWriter)(nil).UpdateNotificationSubject), ctx, userID, params)
}

// UpsertNotification mocks base method.
func (m *MockNotificationWriter) UpsertNotification(ctx context.Context, userID string, params db.UpsertNotificationParams) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotification", ctx, userID, params)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertNotification indicates an expected call of UpsertNotification.
func (mr *MockNotificationWriterMockRecorder) UpsertNotification(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotification", reflect.TypeOf((*MockNotificationWriter)(nil).UpsertNotification), ctx, userID, params)
}

// MockNotificationTagger is a mock of NotificationTagger interface.
type MockNotificationTagger struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationTaggerMockRecorder
	isgomock struct{}
}

// MockNotificationTaggerMockRecorder is the mock recorder for MockNotificationTagger.
type MockNotificationTaggerMockRecorder struct {
	mock *MockNotificationTagger
}

// NewMockNotificationTagger creates a new mock instance.
func NewMockNotificationTagger(ctrl *gomock.Controller) *MockNotificationTagger {
	mock := &MockNotificationTagger{ctrl: ctrl}
	mock.recorder = &MockNotificationTaggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationTagger) EXPECT() *MockNotificationTaggerMockRecorder {
	return m.recorder
}

// AssignTag mocks base method.
func (m *MockNotificationTagger) AssignTag(ctx context.Context, userID, githubID, tagID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTag", ctx, userID, githubID, tagID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignTag indicates an expected call of AssignTag.
func (mr *MockNotificationTaggerMockRecorder) AssignTag(ctx, userID, githubID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTag", reflect.TypeOf((*MockNotificationTagger)(nil).AssignTag), ctx, userID, githubID, tagID)
}

// AssignTagByName mocks base method.
func (m *MockNotificationTagger) AssignTagByName(ctx context.Context, userID, githubID, tagName string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTagByName", ctx, userID, githubID, tagName)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignTagByName indicates an expected call of AssignTagByName.
func (mr *MockNotificationTaggerMockRecorder) AssignTagByName(ctx, userID, githubID, tagName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTagByName", reflect.TypeOf((*MockNotificationTagger)(nil).AssignTagByName), ctx, userID, githubID, tagName)
}

// RemoveTag mocks base method.
func (m *MockNotificationTagger) RemoveTag(ctx context.Context, userID, githubID, tagID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", ctx, userID, githubID, tagID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockNotificationTaggerMockRecorder) RemoveTag(ctx, userID, githubID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockNotificationTagger)(nil).RemoveTag), ctx, userID, githubID, tagID)
}

// MockBulkOperations is a mock of BulkOperations interface.
type MockBulkOperations struct {
	ctrl     *gomock.Controller
	recorder *MockBulkOperationsMockRecorder
	isgomock struct{}
}

// MockBulkOperationsMockRecorder is the mock recorder for MockBulkOperations.
type MockBulkOperationsMockRecorder struct {
	mock *MockBulkOperations
}

// NewMockBulkOperations creates a new mock instance.
func NewMockBulkOperations(ctrl *gomock.Controller) *MockBulkOperations {
	mock := &MockBulkOperations{ctrl: ctrl}
	mock.recorder = &MockBulkOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkOperations) EXPECT() *MockBulkOperationsMockRecorder {
	return m.recorder
}

// BulkAssignTag mocks base method.
func (m *MockBulkOperations) BulkAssignTag(ctx context.Context, userID string, notifications []db.Notification, tagID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAssignTag", ctx, userID, notifications, tagID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkAssignTag indicates an expected call of BulkAssignTag.
func (mr *MockBulkOperationsMockRecorder) BulkAssignTag(ctx, userID, notifications, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAssignTag", reflect.TypeOf((*MockBulkOperations)(nil).BulkAssignTag), ctx, userID, notifications, tagID)
}

// BulkRemoveTag mocks base method.
func (m *MockBulkOperations) BulkRemoveTag(ctx context.Context, userID string, notifications []db.Notification, tagID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkRemoveTag", ctx, userID, notifications, tagID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkRemoveTag indicates an expected call of BulkRemoveTag.
func (mr *MockBulkOperationsMockRecorder) BulkRemoveTag(ctx, userID, notifications, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkRemoveTag", reflect.TypeOf((*MockBulkOperations)(nil).BulkRemoveTag), ctx, userID, notifications, tagID)
}

// BulkUpdate mocks base method.
func (m *MockBulkOperations) BulkUpdate(ctx context.Context, userID string, op models.BulkOperationType, target models.BulkOperationTarget, params models.BulkUpdateParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdate", ctx, userID, op, target, params)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpdate indicates an expected call of BulkUpdate.
func (mr *MockBulkOperationsMockRecorder) BulkUpdate(ctx, userID, op, target, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdate", reflect.TypeOf((*MockBulkOperations)(nil).BulkUpdate), ctx, userID, op, target, params)
}

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// ArchiveNotification mocks base method.
func (m *MockNotificationService) ArchiveNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveNotification indicates an expected call of ArchiveNotification.
func (mr *MockNotificationServiceMockRecorder) ArchiveNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveNotification", reflect.TypeOf((*MockNotificationService)(nil).ArchiveNotification), ctx, userID, githubID)
}

// AssignTag mocks base method.
func (m *MockNotificationService) AssignTag(ctx context.Context, userID, githubID, tagID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTag", ctx, userID, githubID, tagID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignTag indicates an expected call of AssignTag.
func (mr *MockNotificationServiceMockRecorder) AssignTag(ctx, userID, githubID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTag", reflect.TypeOf((*MockNotificationService)(nil).AssignTag), ctx, userID, githubID, tagID)
}

// AssignTagByName mocks base method.
func (m *MockNotificationService) AssignTagByName(ctx context.Context, userID, githubID, tagName string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTagByName", ctx, userID, githubID, tagName)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignTagByName indicates an expected call of AssignTagByName.
func (mr *MockNotificationServiceMockRecorder) AssignTagByName(ctx, userID, githubID, tagName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTagByName", reflect.TypeOf((*MockNotificationService)(nil).AssignTagByName), ctx, userID, githubID, tagName)
}

// BuildResponse mocks base method.
func (m *MockNotificationService) BuildResponse(ctx context.Context, userID string, notification db.Notification, repoMap map[int64]db.Repository, evaluator *eval.Evaluator) (models.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildResponse", ctx, userID, notification, repoMap, evaluator)
	ret0, _ := ret[0].(models.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildResponse indicates an expected call of BuildResponse.
func (mr *MockNotificationServiceMockRecorder) BuildResponse(ctx, userID, notification, repoMap, evaluator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildResponse", reflect.TypeOf((*MockNotificationService)(nil).BuildResponse), ctx, userID, notification, repoMap, evaluator)
}

// BulkAssignTag mocks base method.
func (m *MockNotificationService) BulkAssignTag(ctx context.Context, userID string, notifications []db.Notification, tagID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAssignTag", ctx, userID, notifications, tagID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkAssignTag indicates an expected call of BulkAssignTag.
func (mr *MockNotificationServiceMockRecorder) BulkAssignTag(ctx, userID, notifications, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAssignTag", reflect.TypeOf((*MockNotificationService)(nil).BulkAssignTag), ctx, userID, notifications, tagID)
}

// BulkRemoveTag mocks base method.
func (m *MockNotificationService) BulkRemoveTag(ctx context.Context, userID string, notifications []db.Notification, tagID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkRemoveTag", ctx, userID, notifications, tagID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkRemoveTag indicates an expected call of BulkRemoveTag.
func (mr *MockNotificationServiceMockRecorder) BulkRemoveTag(ctx, userID, notifications, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkRemoveTag", reflect.TypeOf((*MockNotificationService)(nil).BulkRemoveTag), ctx, userID, notifications, tagID)
}

// BulkUpdate mocks base method.
func (m *MockNotificationService) BulkUpdate(ctx context.Context, userID string, op models.BulkOperationType, target models.BulkOperationTarget, params models.BulkUpdateParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdate", ctx, userID, op, target, params)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpdate indicates an expected call of BulkUpdate.
func (mr *MockNotificationServiceMockRecorder) BulkUpdate(ctx, userID, op, target, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdate", reflect.TypeOf((*MockNotificationService)(nil).BulkUpdate), ctx, userID, op, target, params)
}

// GetByGithubID mocks base method.
func (m *MockNotificationService) GetByGithubID(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGithubID", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGithubID indicates an expected call of GetByGithubID.
func (mr *MockNotificationServiceMockRecorder) GetByGithubID(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGithubID", reflect.TypeOf((*MockNotificationService)(nil).GetByGithubID), ctx, userID, githubID)
}

// GetNotificationWithDetails mocks base method.
func (m *MockNotificationService) GetNotificationWithDetails(ctx context.Context, userID, githubID, queryStr string) (models.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationWithDetails", ctx, userID, githubID, queryStr)
	ret0, _ := ret[0].(models.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationWithDetails indicates an expected call of GetNotificationWithDetails.
func (mr *MockNotificationServiceMockRecorder) GetNotificationWithDetails(ctx, userID, githubID, queryStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationWithDetails", reflect.TypeOf((*MockNotificationService)(nil).GetNotificationWithDetails), ctx, userID, githubID, queryStr)
}

// GetTagsForNotification mocks base method.
func (m *MockNotificationService) GetTagsForNotification(ctx context.Context, userID string, notificationID int64) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsForNotification", ctx, userID, notificationID)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsForNotification indicates an expected call of GetTagsForNotification.
func (mr *MockNotificationServiceMockRecorder) GetTagsForNotification(ctx, userID, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsForNotification", reflect.TypeOf((*MockNotificationService)(nil).GetTagsForNotification), ctx, userID, notificationID)
}

// IndexRepositories mocks base method.
func (m *MockNotificationService) IndexRepositories(ctx context.Context, userID string) (map[int64]db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexRepositories", ctx, userID)
	ret0, _ := ret[0].(map[int64]db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexRepositories indicates an expected call of IndexRepositories.
func (mr *MockNotificationServiceMockRecorder) IndexRepositories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexRepositories", reflect.TypeOf((*MockNotificationService)(nil).IndexRepositories), ctx, userID)
}

// ListNotifications mocks base method.
func (m *MockNotificationService) ListNotifications(ctx context.Context, userID string, opts models.ListOptions) (models.ListDetailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, userID, opts)
	ret0, _ := ret[0].(models.ListDetailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockNotificationServiceMockRecorder) ListNotifications(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockNotificationService)(nil).ListNotifications), ctx, userID, opts)
}

// ListNotificationsFromQueryString mocks base method.
func (m *MockNotificationService) ListNotificationsFromQueryString(ctx context.Context, userID, queryStr string, limit int32) ([]db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationsFromQueryString", ctx, userID, queryStr, limit)
	ret0, _ := ret[0].([]db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationsFromQueryString indicates an expected call of ListNotificationsFromQueryString.
func (mr *MockNotificationServiceMockRecorder) ListNotificationsFromQueryString(ctx, userID, queryStr, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationsFromQueryString", reflect.TypeOf((*MockNotificationService)(nil).ListNotificationsFromQueryString), ctx, userID, queryStr, limit)
}

// ListPollNotifications mocks base method.
func (m *MockNotificationService) ListPollNotifications(ctx context.Context, userID string, opts models.ListOptions) (models.ListPollResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPollNotifications", ctx, userID, opts)
	ret0, _ := ret[0].(models.ListPollResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPollNotifications indicates an expected call of ListPollNotifications.
func (mr *MockNotificationServiceMockRecorder) ListPollNotifications(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPollNotifications", reflect.TypeOf((*MockNotificationService)(nil).ListPollNotifications), ctx, userID, opts)
}

// MarkNotificationRead mocks base method.
func (m *MockNotificationService) MarkNotificationRead(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationRead", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationRead indicates an expected call of MarkNotificationRead.
func (mr *MockNotificationServiceMockRecorder) MarkNotificationRead(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationRead", reflect.TypeOf((*MockNotificationService)(nil).MarkNotificationRead), ctx, userID, githubID)
}

// MarkNotificationUnread mocks base method.
func (m *MockNotificationService) MarkNotificationUnread(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationUnread", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationUnread indicates an expected call of MarkNotificationUnread.
func (mr *MockNotificationServiceMockRecorder) MarkNotificationUnread(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationUnread", reflect.TypeOf((*MockNotificationService)(nil).MarkNotificationUnread), ctx, userID, githubID)
}

// MuteNotification mocks base method.
func (m *MockNotificationService) MuteNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MuteNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MuteNotification indicates an expected call of MuteNotification.
func (mr *MockNotificationServiceMockRecorder) MuteNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MuteNotification", reflect.TypeOf((*MockNotificationService)(nil).MuteNotification), ctx, userID, githubID)
}

// NewEvaluator mocks base method.
func (m *MockNotificationService) NewEvaluator(queryStr string) (*eval.Evaluator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEvaluator", queryStr)
	ret0, _ := ret[0].(*eval.Evaluator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewEvaluator indicates an expected call of NewEvaluator.
func (mr *MockNotificationServiceMockRecorder) NewEvaluator(queryStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEvaluator", reflect.TypeOf((*MockNotificationService)(nil).NewEvaluator), queryStr)
}

// RemoveTag mocks base method.
func (m *MockNotificationService) RemoveTag(ctx context.Context, userID, githubID, tagID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", ctx, userID, githubID, tagID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockNotificationServiceMockRecorder) RemoveTag(ctx, userID, githubID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockNotificationService)(nil).RemoveTag), ctx, userID, githubID, tagID)
}

// SnoozeNotification mocks base method.
func (m *MockNotificationService) SnoozeNotification(ctx context.Context, userID, githubID, snoozedUntil string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnoozeNotification", ctx, userID, githubID, snoozedUntil)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnoozeNotification indicates an expected call of SnoozeNotification.
func (mr *MockNotificationServiceMockRecorder) SnoozeNotification(ctx, userID, githubID, snoozedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnoozeNotification", reflect.TypeOf((*MockNotificationService)(nil).SnoozeNotification), ctx, userID, githubID, snoozedUntil)
}

// StarNotification mocks base method.
func (m *MockNotificationService) StarNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StarNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StarNotification indicates an expected call of StarNotification.
func (mr *MockNotificationServiceMockRecorder) StarNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StarNotification", reflect.TypeOf((*MockNotificationService)(nil).StarNotification), ctx, userID, githubID)
}

// UnarchiveNotification mocks base method.
func (m *MockNotificationService) UnarchiveNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnarchiveNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnarchiveNotification indicates an expected call of UnarchiveNotification.
func (mr *MockNotificationServiceMockRecorder) UnarchiveNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnarchiveNotification", reflect.TypeOf((*MockNotificationService)(nil).UnarchiveNotification), ctx, userID, githubID)
}

// UnfilterNotification mocks base method.
func (m *MockNotificationService) UnfilterNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfilterNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnfilterNotification indicates an expected call of UnfilterNotification.
func (mr *MockNotificationServiceMockRecorder) UnfilterNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfilterNotification", reflect.TypeOf((*MockNotificationService)(nil).UnfilterNotification), ctx, userID, githubID)
}

// UnmuteNotification mocks base method.
func (m *MockNotificationService) UnmuteNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmuteNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmuteNotification indicates an expected call of UnmuteNotification.
func (mr *MockNotificationServiceMockRecorder) UnmuteNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmuteNotification", reflect.TypeOf((*MockNotificationService)(nil).UnmuteNotification), ctx, userID, githubID)
}

// UnsnoozeNotification mocks base method.
func (m *MockNotificationService) UnsnoozeNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsnoozeNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsnoozeNotification indicates an expected call of UnsnoozeNotification.
func (mr *MockNotificationServiceMockRecorder) UnsnoozeNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsnoozeNotification", reflect.TypeOf((*MockNotificationService)(nil).UnsnoozeNotification), ctx, userID, githubID)
}

// UnstarNotification mocks base method.
func (m *MockNotificationService) UnstarNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnstarNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnstarNotification indicates an expected call of UnstarNotification.
func (mr *MockNotificationServiceMockRecorder) UnstarNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnstarNotification", reflect.TypeOf((*MockNotificationService)(nil).UnstarNotification), ctx, userID, githubID)
}

// UpdateNotificationSubject mocks base method.
func (m *MockNotificationService) UpdateNotificationSubject(ctx context.Context, userID string, params db.UpdateNotificationSubjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationSubject", ctx, userID, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationSubject indicates an expected call of UpdateNotificationSubject.
func (mr *MockNotificationServiceMockRecorder) UpdateNotificationSubject(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationSubject", reflect.TypeOf((*MockNotificationService)(nil).UpdateNotificationSubject), ctx, userID, params)
}

// UpsertNotification mocks base method.
func (m *MockNotificationService) UpsertNotification(ctx context.Context, userID string, params db.UpsertNotificationParams) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotification", ctx, userID, params)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertNotification indicates an expected call of UpsertNotification.
func (mr *MockNotificationServiceMockRecorder) UpsertNotification(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotification", reflect.TypeOf((*MockNotificationService)(nil).UpsertNotification), ctx, userID, params)
}
