// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/auth/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/auth/service.go -destination=internal/core/auth/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	models "github.com/octobud-hq/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// EnsureUser mocks base method.
func (m *MockAuthService) EnsureUser(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUser", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureUser indicates an expected call of EnsureUser.
func (mr *MockAuthServiceMockRecorder) EnsureUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUser", reflect.TypeOf((*MockAuthService)(nil).EnsureUser), ctx)
}

// GetUser mocks base method.
func (m *MockAuthService) GetUser(ctx context.Context) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthServiceMockRecorder) GetUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAuthService)(nil).GetUser), ctx)
}

// GetUserSyncSettings mocks base method.
func (m *MockAuthService) GetUserSyncSettings(ctx context.Context) (*models.SyncSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSyncSettings", ctx)
	ret0, _ := ret[0].(*models.SyncSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSyncSettings indicates an expected call of GetUserSyncSettings.
func (mr *MockAuthServiceMockRecorder) GetUserSyncSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSyncSettings", reflect.TypeOf((*MockAuthService)(nil).GetUserSyncSettings), ctx)
}

// GetUserUpdateSettings mocks base method.
func (m *MockAuthService) GetUserUpdateSettings(ctx context.Context) (*models.UpdateSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserUpdateSettings", ctx)
	ret0, _ := ret[0].(*models.UpdateSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserUpdateSettings indicates an expected call of GetUserUpdateSettings.
func (mr *MockAuthServiceMockRecorder) GetUserUpdateSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserUpdateSettings", reflect.TypeOf((*MockAuthService)(nil).GetUserUpdateSettings), ctx)
}

// HasGitHubIdentity mocks base method.
func (m *MockAuthService) HasGitHubIdentity(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasGitHubIdentity", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasGitHubIdentity indicates an expected call of HasGitHubIdentity.
func (mr *MockAuthServiceMockRecorder) HasGitHubIdentity(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasGitHubIdentity", reflect.TypeOf((*MockAuthService)(nil).HasGitHubIdentity), ctx)
}

// HasSyncSettings mocks base method.
func (m *MockAuthService) HasSyncSettings(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSyncSettings", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSyncSettings indicates an expected call of HasSyncSettings.
func (mr *MockAuthServiceMockRecorder) HasSyncSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSyncSettings", reflect.TypeOf((*MockAuthService)(nil).HasSyncSettings), ctx)
}

// UpdateGitHubIdentity mocks base method.
func (m *MockAuthService) UpdateGitHubIdentity(ctx context.Context, githubUserID, githubUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGitHubIdentity", ctx, githubUserID, githubUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGitHubIdentity indicates an expected call of UpdateGitHubIdentity.
func (mr *MockAuthServiceMockRecorder) UpdateGitHubIdentity(ctx, githubUserID, githubUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGitHubIdentity", reflect.TypeOf((*MockAuthService)(nil).UpdateGitHubIdentity), ctx, githubUserID, githubUsername)
}

// UpdateUserMutedUntil mocks base method.
func (m *MockAuthService) UpdateUserMutedUntil(ctx context.Context, mutedUntil sql.NullTime) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserMutedUntil", ctx, mutedUntil)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserMutedUntil indicates an expected call of UpdateUserMutedUntil.
func (mr *MockAuthServiceMockRecorder) UpdateUserMutedUntil(ctx, mutedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserMutedUntil", reflect.TypeOf((*MockAuthService)(nil).UpdateUserMutedUntil), ctx, mutedUntil)
}

// UpdateUserSyncSettings mocks base method.
func (m *MockAuthService) UpdateUserSyncSettings(ctx context.Context, settings *models.SyncSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserSyncSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserSyncSettings indicates an expected call of UpdateUserSyncSettings.
func (mr *MockAuthServiceMockRecorder) UpdateUserSyncSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserSyncSettings", reflect.TypeOf((*MockAuthService)(nil).UpdateUserSyncSettings), ctx, settings)
}

// UpdateUserUpdateSettings mocks base method.
func (m *MockAuthService) UpdateUserUpdateSettings(ctx context.Context, settings *models.UpdateSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserUpdateSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserUpdateSettings indicates an expected call of UpdateUserUpdateSettings.
func (mr *MockAuthServiceMockRecorder) UpdateUserUpdateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserUpdateSettings", reflect.TypeOf((*MockAuthService)(nil).UpdateUserUpdateSettings), ctx, settings)
}
