// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/sync/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/sync/service.go -destination=internal/core/sync/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/octobud-hq/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncService is a mock of SyncService interface.
type MockSyncService struct {
	ctrl     *gomock.Controller
	recorder *MockSyncServiceMockRecorder
	isgomock struct{}
}

// MockSyncServiceMockRecorder is the mock recorder for MockSyncService.
type MockSyncServiceMockRecorder struct {
	mock *MockSyncService
}

// NewMockSyncService creates a new mock instance.
func NewMockSyncService(ctrl *gomock.Controller) *MockSyncService {
	mock := &MockSyncService{ctrl: ctrl}
	mock.recorder = &MockSyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncService) EXPECT() *MockSyncServiceMockRecorder {
	return m.recorder
}

// GetSyncState mocks base method.
func (m *MockSyncService) GetSyncState(ctx context.Context) (models.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncState", ctx)
	ret0, _ := ret[0].(models.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncState indicates an expected call of GetSyncState.
func (mr *MockSyncServiceMockRecorder) GetSyncState(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncState", reflect.TypeOf((*MockSyncService)(nil).GetSyncState), ctx)
}

// UpsertSyncState mocks base method.
func (m *MockSyncService) UpsertSyncState(ctx context.Context, lastSuccessfulPoll, latestNotificationAt *time.Time) (models.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSyncState", ctx, lastSuccessfulPoll, latestNotificationAt)
	ret0, _ := ret[0].(models.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSyncState indicates an expected call of UpsertSyncState.
func (mr *MockSyncServiceMockRecorder) UpsertSyncState(ctx, lastSuccessfulPoll, latestNotificationAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSyncState", reflect.TypeOf((*MockSyncService)(nil).UpsertSyncState), ctx, lastSuccessfulPoll, latestNotificationAt)
}
