// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/syncstate/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/syncstate/service.go -destination=internal/core/syncstate/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/octobud-hq/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncStateService is a mock of SyncStateService interface.
type MockSyncStateService struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStateServiceMockRecorder
	isgomock struct{}
}

// MockSyncStateServiceMockRecorder is the mock recorder for MockSyncStateService.
type MockSyncStateServiceMockRecorder struct {
	mock *MockSyncStateService
}

// NewMockSyncStateService creates a new mock instance.
func NewMockSyncStateService(ctrl *gomock.Controller) *MockSyncStateService {
	mock := &MockSyncStateService{ctrl: ctrl}
	mock.recorder = &MockSyncStateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStateService) EXPECT() *MockSyncStateServiceMockRecorder {
	return m.recorder
}

// GetSyncState mocks base method.
func (m *MockSyncStateService) GetSyncState(ctx context.Context, userID string) (models.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncState", ctx, userID)
	ret0, _ := ret[0].(models.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncState indicates an expected call of GetSyncState.
func (mr *MockSyncStateServiceMockRecorder) GetSyncState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncState", reflect.TypeOf((*MockSyncStateService)(nil).GetSyncState), ctx, userID)
}

// UpsertSyncState mocks base method.
func (m *MockSyncStateService) UpsertSyncState(ctx context.Context, userID string, lastSuccessfulPoll, latestNotificationAt *time.Time) (models.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSyncState", ctx, userID, lastSuccessfulPoll, latestNotificationAt)
	ret0, _ := ret[0].(models.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSyncState indicates an expected call of UpsertSyncState.
func (mr *MockSyncStateServiceMockRecorder) UpsertSyncState(ctx, userID, lastSuccessfulPoll, latestNotificationAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSyncState", reflect.TypeOf((*MockSyncStateService)(nil).UpsertSyncState), ctx, userID, lastSuccessfulPoll, latestNotificationAt)
}
