// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/timeline/timeline.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/timeline/timeline.go -destination=internal/core/timeline/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	githubinterfaces "github.com/octobud-hq/octobud/backend/internal/github/interfaces"
	types "github.com/octobud-hq/octobud/backend/internal/github/types"
	models "github.com/octobud-hq/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTimelineService is a mock of TimelineService interface.
type MockTimelineService struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineServiceMockRecorder
	isgomock struct{}
}

// MockTimelineServiceMockRecorder is the mock recorder for MockTimelineService.
type MockTimelineServiceMockRecorder struct {
	mock *MockTimelineService
}

// NewMockTimelineService creates a new mock instance.
func NewMockTimelineService(ctrl *gomock.Controller) *MockTimelineService {
	mock := &MockTimelineService{ctrl: ctrl}
	mock.recorder = &MockTimelineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineService) EXPECT() *MockTimelineServiceMockRecorder {
	return m.recorder
}

// FetchFilteredTimeline mocks base method.
func (m *MockTimelineService) FetchFilteredTimeline(ctx context.Context, client githubinterfaces.Client, subjectInfo *types.SubjectInfo, perPage, page int) (*models.TimelineResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFilteredTimeline", ctx, client, subjectInfo, perPage, page)
	ret0, _ := ret[0].(*models.TimelineResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFilteredTimeline indicates an expected call of FetchFilteredTimeline.
func (mr *MockTimelineServiceMockRecorder) FetchFilteredTimeline(ctx, client, subjectInfo, perPage, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFilteredTimeline", reflect.TypeOf((*MockTimelineService)(nil).FetchFilteredTimeline), ctx, client, subjectInfo, perPage, page)
}
