// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/octobud-hq/octobud/backend/internal/sync (interfaces: SyncOperations)
//
// Generated by this command:
//
//	mockgen -destination=internal/sync/mocks/mock_sync.go -package=syncmocks github.com/octobud-hq/octobud/backend/internal/sync SyncOperations
//

// Package syncmocks is a generated GoMock package.
package syncmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	githubinterfaces "github.com/octobud-hq/octobud/backend/internal/github/interfaces"
	types "github.com/octobud-hq/octobud/backend/internal/github/types"
	sync "github.com/octobud-hq/octobud/backend/internal/sync"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncOperations is a mock of SyncOperations interface.
type MockSyncOperations struct {
	ctrl     *gomock.Controller
	recorder *MockSyncOperationsMockRecorder
	isgomock struct{}
}

// MockSyncOperationsMockRecorder is the mock recorder for MockSyncOperations.
type MockSyncOperationsMockRecorder struct {
	mock *MockSyncOperations
}

// NewMockSyncOperations creates a new mock instance.
func NewMockSyncOperations(ctrl *gomock.Controller) *MockSyncOperations {
	mock := &MockSyncOperations{ctrl: ctrl}
	mock.recorder = &MockSyncOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncOperations) EXPECT() *MockSyncOperationsMockRecorder {
	return m.recorder
}

// FetchNotificationsToSync mocks base method.
func (m *MockSyncOperations) FetchNotificationsToSync(ctx context.Context, syncCtx sync.SyncContext) ([]types.NotificationThread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNotificationsToSync", ctx, syncCtx)
	ret0, _ := ret[0].([]types.NotificationThread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNotificationsToSync indicates an expected call of FetchNotificationsToSync.
func (mr *MockSyncOperationsMockRecorder) FetchNotificationsToSync(ctx, syncCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNotificationsToSync", reflect.TypeOf((*MockSyncOperations)(nil).FetchNotificationsToSync), ctx, syncCtx)
}

// FetchOlderNotificationsToSync mocks base method.
func (m *MockSyncOperations) FetchOlderNotificationsToSync(ctx context.Context, since, until time.Time, maxCount *int, unreadOnly bool) ([]types.NotificationThread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOlderNotificationsToSync", ctx, since, until, maxCount, unreadOnly)
	ret0, _ := ret[0].([]types.NotificationThread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOlderNotificationsToSync indicates an expected call of FetchOlderNotificationsToSync.
func (mr *MockSyncOperationsMockRecorder) FetchOlderNotificationsToSync(ctx, since, until, maxCount, unreadOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOlderNotificationsToSync", reflect.TypeOf((*MockSyncOperations)(nil).FetchOlderNotificationsToSync), ctx, since, until, maxCount, unreadOnly)
}

// GetSyncContext mocks base method.
func (m *MockSyncOperations) GetSyncContext(ctx context.Context, userID string) (sync.SyncContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncContext", ctx, userID)
	ret0, _ := ret[0].(sync.SyncContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncContext indicates an expected call of GetSyncContext.
func (mr *MockSyncOperationsMockRecorder) GetSyncContext(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncContext", reflect.TypeOf((*MockSyncOperations)(nil).GetSyncContext), ctx, userID)
}

// IsInitialSyncComplete mocks base method.
func (m *MockSyncOperations) IsInitialSyncComplete(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialSyncComplete", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsInitialSyncComplete indicates an expected call of IsInitialSyncComplete.
func (mr *MockSyncOperationsMockRecorder) IsInitialSyncComplete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialSyncComplete", reflect.TypeOf((*MockSyncOperations)(nil).IsInitialSyncComplete), ctx, userID)
}

// ProcessNotification mocks base method.
func (m *MockSyncOperations) ProcessNotification(ctx context.Context, userID string, thread types.NotificationThread) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNotification", ctx, userID, thread)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessNotification indicates an expected call of ProcessNotification.
func (mr *MockSyncOperationsMockRecorder) ProcessNotification(ctx, userID, thread any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNotification", reflect.TypeOf((*MockSyncOperations)(nil).ProcessNotification), ctx, userID, thread)
}

// ProcessNotificationData mocks base method.
func (m *MockSyncOperations) ProcessNotificationData(ctx context.Context, userID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNotificationData", ctx, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessNotificationData indicates an expected call of ProcessNotificationData.
func (mr *MockSyncOperationsMockRecorder) ProcessNotificationData(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNotificationData", reflect.TypeOf((*MockSyncOperations)(nil).ProcessNotificationData), ctx, userID, data)
}

// RefreshSubjectData mocks base method.
func (m *MockSyncOperations) RefreshSubjectData(ctx context.Context, userID, githubID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSubjectData", ctx, userID, githubID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshSubjectData indicates an expected call of RefreshSubjectData.
func (mr *MockSyncOperationsMockRecorder) RefreshSubjectData(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSubjectData", reflect.TypeOf((*MockSyncOperations)(nil).RefreshSubjectData), ctx, userID, githubID)
}

// UpdateSyncStateAfterProcessing mocks base method.
func (m *MockSyncOperations) UpdateSyncStateAfterProcessing(ctx context.Context, userID string, latestUpdate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncStateAfterProcessing", ctx, userID, latestUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncStateAfterProcessing indicates an expected call of UpdateSyncStateAfterProcessing.
func (mr *MockSyncOperationsMockRecorder) UpdateSyncStateAfterProcessing(ctx, userID, latestUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncStateAfterProcessing", reflect.TypeOf((*MockSyncOperations)(nil).UpdateSyncStateAfterProcessing), ctx, userID, latestUpdate)
}

// UpdateSyncStateAfterProcessingWithInitialSync mocks base method.
func (m *MockSyncOperations) UpdateSyncStateAfterProcessingWithInitialSync(ctx context.Context, userID string, latestUpdate time.Time, initialSyncCompletedAt, oldestNotificationSyncedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncStateAfterProcessingWithInitialSync", ctx, userID, latestUpdate, initialSyncCompletedAt, oldestNotificationSyncedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncStateAfterProcessingWithInitialSync indicates an expected call of UpdateSyncStateAfterProcessingWithInitialSync.
func (mr *MockSyncOperationsMockRecorder) UpdateSyncStateAfterProcessingWithInitialSync(ctx, userID, latestUpdate, initialSyncCompletedAt, oldestNotificationSyncedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncStateAfterProcessingWithInitialSync", reflect.TypeOf((*MockSyncOperations)(nil).UpdateSyncStateAfterProcessingWithInitialSync), ctx, userID, latestUpdate, initialSyncCompletedAt, oldestNotificationSyncedAt)
}

// WithClient mocks base method.
func (m *MockSyncOperations) WithClient(client githubinterfaces.Client) sync.SyncOperations {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithClient", client)
	ret0, _ := ret[0].(sync.SyncOperations)
	return ret0
}

// WithClient indicates an expected call of WithClient.
func (mr *MockSyncOperationsMockRecorder) WithClient(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithClient", reflect.TypeOf((*MockSyncOperations)(nil).WithClient), client)
}
