// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/store.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/store.go -destination=internal/db/mocks/mock_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	db "github.com/octobud-hq/octobud/backend/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ArchiveNotification mocks base method.
func (m *MockStore) ArchiveNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveNotification indicates an expected call of ArchiveNotification.
func (mr *MockStoreMockRecorder) ArchiveNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveNotification", reflect.TypeOf((*MockStore)(nil).ArchiveNotification), ctx, userID, githubID)
}

// AssignTagToEntity mocks base method.
func (m *MockStore) AssignTagToEntity(ctx context.Context, userID string, arg db.AssignTagToEntityParams) (db.TagAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTagToEntity", ctx, userID, arg)
	ret0, _ := ret[0].(db.TagAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignTagToEntity indicates an expected call of AssignTagToEntity.
func (mr *MockStoreMockRecorder) AssignTagToEntity(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTagToEntity", reflect.TypeOf((*MockStore)(nil).AssignTagToEntity), ctx, userID, arg)
}

// BulkArchiveNotifications mocks base method.
func (m *MockStore) BulkArchiveNotifications(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkArchiveNotifications", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkArchiveNotifications indicates an expected call of BulkArchiveNotifications.
func (mr *MockStoreMockRecorder) BulkArchiveNotifications(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkArchiveNotifications", reflect.TypeOf((*MockStore)(nil).BulkArchiveNotifications), ctx, userID, githubIDs)
}

// BulkArchiveNotificationsByQuery mocks base method.
func (m *MockStore) BulkArchiveNotificationsByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkArchiveNotificationsByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkArchiveNotificationsByQuery indicates an expected call of BulkArchiveNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkArchiveNotificationsByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkArchiveNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkArchiveNotificationsByQuery), ctx, userID, query)
}

// BulkMarkNotificationsRead mocks base method.
func (m *MockStore) BulkMarkNotificationsRead(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsRead", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsRead indicates an expected call of BulkMarkNotificationsRead.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsRead(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsRead", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsRead), ctx, userID, githubIDs)
}

// BulkMarkNotificationsReadByQuery mocks base method.
func (m *MockStore) BulkMarkNotificationsReadByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsReadByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsReadByQuery indicates an expected call of BulkMarkNotificationsReadByQuery.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsReadByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsReadByQuery", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsReadByQuery), ctx, userID, query)
}

// BulkMarkNotificationsUnfiltered mocks base method.
func (m *MockStore) BulkMarkNotificationsUnfiltered(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsUnfiltered", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsUnfiltered indicates an expected call of BulkMarkNotificationsUnfiltered.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsUnfiltered(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsUnfiltered", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsUnfiltered), ctx, userID, githubIDs)
}

// BulkMarkNotificationsUnread mocks base method.
func (m *MockStore) BulkMarkNotificationsUnread(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsUnread", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsUnread indicates an expected call of BulkMarkNotificationsUnread.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsUnread(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsUnread", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsUnread), ctx, userID, githubIDs)
}

// BulkMarkNotificationsUnreadByQuery mocks base method.
func (m *MockStore) BulkMarkNotificationsUnreadByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsUnreadByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsUnreadByQuery indicates an expected call of BulkMarkNotificationsUnreadByQuery.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsUnreadByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsUnreadByQuery", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsUnreadByQuery), ctx, userID, query)
}

// BulkMuteNotifications mocks base method.
func (m *MockStore) BulkMuteNotifications(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMuteNotifications", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMuteNotifications indicates an expected call of BulkMuteNotifications.
func (mr *MockStoreMockRecorder) BulkMuteNotifications(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMuteNotifications", reflect.TypeOf((*MockStore)(nil).BulkMuteNotifications), ctx, userID, githubIDs)
}

// BulkMuteNotificationsByQuery mocks base method.
func (m *MockStore) BulkMuteNotificationsByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMuteNotificationsByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMuteNotificationsByQuery indicates an expected call of BulkMuteNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkMuteNotificationsByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMuteNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkMuteNotificationsByQuery), ctx, userID, query)
}

// BulkSnoozeNotifications mocks base method.
func (m *MockStore) BulkSnoozeNotifications(ctx context.Context, userID string, arg db.BulkSnoozeNotificationsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSnoozeNotifications", ctx, userID, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkSnoozeNotifications indicates an expected call of BulkSnoozeNotifications.
func (mr *MockStoreMockRecorder) BulkSnoozeNotifications(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSnoozeNotifications", reflect.TypeOf((*MockStore)(nil).BulkSnoozeNotifications), ctx, userID, arg)
}

// BulkSnoozeNotificationsByQuery mocks base method.
func (m *MockStore) BulkSnoozeNotificationsByQuery(ctx context.Context, userID string, arg db.BulkSnoozeNotificationsByQueryParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSnoozeNotificationsByQuery", ctx, userID, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkSnoozeNotificationsByQuery indicates an expected call of BulkSnoozeNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkSnoozeNotificationsByQuery(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSnoozeNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkSnoozeNotificationsByQuery), ctx, userID, arg)
}

// BulkStarNotifications mocks base method.
func (m *MockStore) BulkStarNotifications(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkStarNotifications", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkStarNotifications indicates an expected call of BulkStarNotifications.
func (mr *MockStoreMockRecorder) BulkStarNotifications(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkStarNotifications", reflect.TypeOf((*MockStore)(nil).BulkStarNotifications), ctx, userID, githubIDs)
}

// BulkStarNotificationsByQuery mocks base method.
func (m *MockStore) BulkStarNotificationsByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkStarNotificationsByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkStarNotificationsByQuery indicates an expected call of BulkStarNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkStarNotificationsByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkStarNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkStarNotificationsByQuery), ctx, userID, query)
}

// BulkUnarchiveNotifications mocks base method.
func (m *MockStore) BulkUnarchiveNotifications(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnarchiveNotifications", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnarchiveNotifications indicates an expected call of BulkUnarchiveNotifications.
func (mr *MockStoreMockRecorder) BulkUnarchiveNotifications(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnarchiveNotifications", reflect.TypeOf((*MockStore)(nil).BulkUnarchiveNotifications), ctx, userID, githubIDs)
}

// BulkUnarchiveNotificationsByQuery mocks base method.
func (m *MockStore) BulkUnarchiveNotificationsByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnarchiveNotificationsByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnarchiveNotificationsByQuery indicates an expected call of BulkUnarchiveNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkUnarchiveNotificationsByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnarchiveNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkUnarchiveNotificationsByQuery), ctx, userID, query)
}

// BulkUnmuteNotifications mocks base method.
func (m *MockStore) BulkUnmuteNotifications(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnmuteNotifications", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnmuteNotifications indicates an expected call of BulkUnmuteNotifications.
func (mr *MockStoreMockRecorder) BulkUnmuteNotifications(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnmuteNotifications", reflect.TypeOf((*MockStore)(nil).BulkUnmuteNotifications), ctx, userID, githubIDs)
}

// BulkUnmuteNotificationsByQuery mocks base method.
func (m *MockStore) BulkUnmuteNotificationsByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnmuteNotificationsByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnmuteNotificationsByQuery indicates an expected call of BulkUnmuteNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkUnmuteNotificationsByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnmuteNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkUnmuteNotificationsByQuery), ctx, userID, query)
}

// BulkUnsnoozeNotifications mocks base method.
func (m *MockStore) BulkUnsnoozeNotifications(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnsnoozeNotifications", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnsnoozeNotifications indicates an expected call of BulkUnsnoozeNotifications.
func (mr *MockStoreMockRecorder) BulkUnsnoozeNotifications(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnsnoozeNotifications", reflect.TypeOf((*MockStore)(nil).BulkUnsnoozeNotifications), ctx, userID, githubIDs)
}

// BulkUnsnoozeNotificationsByQuery mocks base method.
func (m *MockStore) BulkUnsnoozeNotificationsByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnsnoozeNotificationsByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnsnoozeNotificationsByQuery indicates an expected call of BulkUnsnoozeNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkUnsnoozeNotificationsByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnsnoozeNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkUnsnoozeNotificationsByQuery), ctx, userID, query)
}

// BulkUnstarNotifications mocks base method.
func (m *MockStore) BulkUnstarNotifications(ctx context.Context, userID string, githubIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnstarNotifications", ctx, userID, githubIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnstarNotifications indicates an expected call of BulkUnstarNotifications.
func (mr *MockStoreMockRecorder) BulkUnstarNotifications(ctx, userID, githubIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnstarNotifications", reflect.TypeOf((*MockStore)(nil).BulkUnstarNotifications), ctx, userID, githubIDs)
}

// BulkUnstarNotificationsByQuery mocks base method.
func (m *MockStore) BulkUnstarNotificationsByQuery(ctx context.Context, userID string, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnstarNotificationsByQuery", ctx, userID, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnstarNotificationsByQuery indicates an expected call of BulkUnstarNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkUnstarNotificationsByQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnstarNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkUnstarNotificationsByQuery), ctx, userID, query)
}

// ClearUserGitHubToken mocks base method.
func (m *MockStore) ClearUserGitHubToken(ctx context.Context) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearUserGitHubToken", ctx)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearUserGitHubToken indicates an expected call of ClearUserGitHubToken.
func (mr *MockStoreMockRecorder) ClearUserGitHubToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearUserGitHubToken", reflect.TypeOf((*MockStore)(nil).ClearUserGitHubToken), ctx)
}

// CountEligibleForCleanup mocks base method.
func (m *MockStore) CountEligibleForCleanup(ctx context.Context, userID string, params db.CleanupParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEligibleForCleanup", ctx, userID, params)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEligibleForCleanup indicates an expected call of CountEligibleForCleanup.
func (mr *MockStoreMockRecorder) CountEligibleForCleanup(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEligibleForCleanup", reflect.TypeOf((*MockStore)(nil).CountEligibleForCleanup), ctx, userID, params)
}

// CreateRule mocks base method.
func (m *MockStore) CreateRule(ctx context.Context, userID string, arg db.CreateRuleParams) (db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, userID, arg)
	ret0, _ := ret[0].(db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockStoreMockRecorder) CreateRule(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockStore)(nil).CreateRule), ctx, userID, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx)
}

// CreateView mocks base method.
func (m *MockStore) CreateView(ctx context.Context, userID string, arg db.CreateViewParams) (db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateView", ctx, userID, arg)
	ret0, _ := ret[0].(db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateView indicates an expected call of CreateView.
func (mr *MockStoreMockRecorder) CreateView(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateView", reflect.TypeOf((*MockStore)(nil).CreateView), ctx, userID, arg)
}

// DeleteAllGitHubData mocks base method.
func (m *MockStore) DeleteAllGitHubData(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllGitHubData", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllGitHubData indicates an expected call of DeleteAllGitHubData.
func (mr *MockStoreMockRecorder) DeleteAllGitHubData(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllGitHubData", reflect.TypeOf((*MockStore)(nil).DeleteAllGitHubData), ctx, userID)
}

// DeleteOldArchivedNotifications mocks base method.
func (m *MockStore) DeleteOldArchivedNotifications(ctx context.Context, userID string, params db.CleanupParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldArchivedNotifications", ctx, userID, params)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOldArchivedNotifications indicates an expected call of DeleteOldArchivedNotifications.
func (mr *MockStoreMockRecorder) DeleteOldArchivedNotifications(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldArchivedNotifications", reflect.TypeOf((*MockStore)(nil).DeleteOldArchivedNotifications), ctx, userID, params)
}

// DeleteOrphanedPullRequests mocks base method.
func (m *MockStore) DeleteOrphanedPullRequests(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrphanedPullRequests", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrphanedPullRequests indicates an expected call of DeleteOrphanedPullRequests.
func (mr *MockStoreMockRecorder) DeleteOrphanedPullRequests(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrphanedPullRequests", reflect.TypeOf((*MockStore)(nil).DeleteOrphanedPullRequests), ctx, userID)
}

// DeleteRule mocks base method.
func (m *MockStore) DeleteRule(ctx context.Context, userID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockStoreMockRecorder) DeleteRule(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockStore)(nil).DeleteRule), ctx, userID, id)
}

// DeleteTag mocks base method.
func (m *MockStore) DeleteTag(ctx context.Context, userID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockStoreMockRecorder) DeleteTag(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockStore)(nil).DeleteTag), ctx, userID, id)
}

// DeleteView mocks base method.
func (m *MockStore) DeleteView(ctx context.Context, userID, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteView", ctx, userID, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteView indicates an expected call of DeleteView.
func (mr *MockStoreMockRecorder) DeleteView(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteView", reflect.TypeOf((*MockStore)(nil).DeleteView), ctx, userID, id)
}

// GetNotificationByGithubID mocks base method.
func (m *MockStore) GetNotificationByGithubID(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationByGithubID", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationByGithubID indicates an expected call of GetNotificationByGithubID.
func (mr *MockStoreMockRecorder) GetNotificationByGithubID(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationByGithubID", reflect.TypeOf((*MockStore)(nil).GetNotificationByGithubID), ctx, userID, githubID)
}

// GetNotificationByID mocks base method.
func (m *MockStore) GetNotificationByID(ctx context.Context, userID string, id int64) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationByID", ctx, userID, id)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationByID indicates an expected call of GetNotificationByID.
func (mr *MockStoreMockRecorder) GetNotificationByID(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationByID", reflect.TypeOf((*MockStore)(nil).GetNotificationByID), ctx, userID, id)
}

// GetRepositoryByID mocks base method.
func (m *MockStore) GetRepositoryByID(ctx context.Context, userID string, id int64) (db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByID", ctx, userID, id)
	ret0, _ := ret[0].(db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByID indicates an expected call of GetRepositoryByID.
func (mr *MockStoreMockRecorder) GetRepositoryByID(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByID", reflect.TypeOf((*MockStore)(nil).GetRepositoryByID), ctx, userID, id)
}

// GetRule mocks base method.
func (m *MockStore) GetRule(ctx context.Context, userID, id string) (db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, userID, id)
	ret0, _ := ret[0].(db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockStoreMockRecorder) GetRule(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockStore)(nil).GetRule), ctx, userID, id)
}

// GetRulesByViewID mocks base method.
func (m *MockStore) GetRulesByViewID(ctx context.Context, userID string, viewID sql.NullString) ([]db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesByViewID", ctx, userID, viewID)
	ret0, _ := ret[0].([]db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRulesByViewID indicates an expected call of GetRulesByViewID.
func (mr *MockStoreMockRecorder) GetRulesByViewID(ctx, userID, viewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesByViewID", reflect.TypeOf((*MockStore)(nil).GetRulesByViewID), ctx, userID, viewID)
}

// GetStorageStats mocks base method.
func (m *MockStore) GetStorageStats(ctx context.Context, userID string) (db.StorageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageStats", ctx, userID)
	ret0, _ := ret[0].(db.StorageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageStats indicates an expected call of GetStorageStats.
func (mr *MockStoreMockRecorder) GetStorageStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageStats", reflect.TypeOf((*MockStore)(nil).GetStorageStats), ctx, userID)
}

// GetSyncState mocks base method.
func (m *MockStore) GetSyncState(ctx context.Context, userID string) (db.GetSyncStateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncState", ctx, userID)
	ret0, _ := ret[0].(db.GetSyncStateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncState indicates an expected call of GetSyncState.
func (mr *MockStoreMockRecorder) GetSyncState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncState", reflect.TypeOf((*MockStore)(nil).GetSyncState), ctx, userID)
}

// GetTag mocks base method.
func (m *MockStore) GetTag(ctx context.Context, userID, id string) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTag", ctx, userID, id)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag.
func (mr *MockStoreMockRecorder) GetTag(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockStore)(nil).GetTag), ctx, userID, id)
}

// GetTagByName mocks base method.
func (m *MockStore) GetTagByName(ctx context.Context, userID, name string) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByName", ctx, userID, name)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByName indicates an expected call of GetTagByName.
func (mr *MockStoreMockRecorder) GetTagByName(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByName", reflect.TypeOf((*MockStore)(nil).GetTagByName), ctx, userID, name)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx)
}

// GetView mocks base method.
func (m *MockStore) GetView(ctx context.Context, userID, id string) (db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetView", ctx, userID, id)
	ret0, _ := ret[0].(db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetView indicates an expected call of GetView.
func (mr *MockStoreMockRecorder) GetView(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetView", reflect.TypeOf((*MockStore)(nil).GetView), ctx, userID, id)
}

// ListAllTags mocks base method.
func (m *MockStore) ListAllTags(ctx context.Context, userID string) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllTags", ctx, userID)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllTags indicates an expected call of ListAllTags.
func (mr *MockStoreMockRecorder) ListAllTags(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllTags", reflect.TypeOf((*MockStore)(nil).ListAllTags), ctx, userID)
}

// ListEnabledRulesOrdered mocks base method.
func (m *MockStore) ListEnabledRulesOrdered(ctx context.Context, userID string) ([]db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledRulesOrdered", ctx, userID)
	ret0, _ := ret[0].([]db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledRulesOrdered indicates an expected call of ListEnabledRulesOrdered.
func (mr *MockStoreMockRecorder) ListEnabledRulesOrdered(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledRulesOrdered", reflect.TypeOf((*MockStore)(nil).ListEnabledRulesOrdered), ctx, userID)
}

// ListNotificationsFromQuery mocks base method.
func (m *MockStore) ListNotificationsFromQuery(ctx context.Context, userID string, query db.NotificationQuery) (db.ListNotificationsFromQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationsFromQuery", ctx, userID, query)
	ret0, _ := ret[0].(db.ListNotificationsFromQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationsFromQuery indicates an expected call of ListNotificationsFromQuery.
func (mr *MockStoreMockRecorder) ListNotificationsFromQuery(ctx, userID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationsFromQuery", reflect.TypeOf((*MockStore)(nil).ListNotificationsFromQuery), ctx, userID, query)
}

// ListRepositories mocks base method.
func (m *MockStore) ListRepositories(ctx context.Context, userID string) ([]db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositories", ctx, userID)
	ret0, _ := ret[0].([]db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockStoreMockRecorder) ListRepositories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*MockStore)(nil).ListRepositories), ctx, userID)
}

// ListRules mocks base method.
func (m *MockStore) ListRules(ctx context.Context, userID string) ([]db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, userID)
	ret0, _ := ret[0].([]db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockStoreMockRecorder) ListRules(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockStore)(nil).ListRules), ctx, userID)
}

// ListTagsForEntity mocks base method.
func (m *MockStore) ListTagsForEntity(ctx context.Context, userID string, arg db.ListTagsForEntityParams) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsForEntity", ctx, userID, arg)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForEntity indicates an expected call of ListTagsForEntity.
func (mr *MockStoreMockRecorder) ListTagsForEntity(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForEntity", reflect.TypeOf((*MockStore)(nil).ListTagsForEntity), ctx, userID, arg)
}

// ListViews mocks base method.
func (m *MockStore) ListViews(ctx context.Context, userID string) ([]db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListViews", ctx, userID)
	ret0, _ := ret[0].([]db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListViews indicates an expected call of ListViews.
func (mr *MockStoreMockRecorder) ListViews(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListViews", reflect.TypeOf((*MockStore)(nil).ListViews), ctx, userID)
}

// MarkNotificationFiltered mocks base method.
func (m *MockStore) MarkNotificationFiltered(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationFiltered", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationFiltered indicates an expected call of MarkNotificationFiltered.
func (mr *MockStoreMockRecorder) MarkNotificationFiltered(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationFiltered", reflect.TypeOf((*MockStore)(nil).MarkNotificationFiltered), ctx, userID, githubID)
}

// MarkNotificationRead mocks base method.
func (m *MockStore) MarkNotificationRead(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationRead", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationRead indicates an expected call of MarkNotificationRead.
func (mr *MockStoreMockRecorder) MarkNotificationRead(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationRead", reflect.TypeOf((*MockStore)(nil).MarkNotificationRead), ctx, userID, githubID)
}

// MarkNotificationUnfiltered mocks base method.
func (m *MockStore) MarkNotificationUnfiltered(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationUnfiltered", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationUnfiltered indicates an expected call of MarkNotificationUnfiltered.
func (mr *MockStoreMockRecorder) MarkNotificationUnfiltered(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationUnfiltered", reflect.TypeOf((*MockStore)(nil).MarkNotificationUnfiltered), ctx, userID, githubID)
}

// MarkNotificationUnread mocks base method.
func (m *MockStore) MarkNotificationUnread(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationUnread", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationUnread indicates an expected call of MarkNotificationUnread.
func (mr *MockStoreMockRecorder) MarkNotificationUnread(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationUnread", reflect.TypeOf((*MockStore)(nil).MarkNotificationUnread), ctx, userID, githubID)
}

// MuteNotification mocks base method.
func (m *MockStore) MuteNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MuteNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MuteNotification indicates an expected call of MuteNotification.
func (mr *MockStoreMockRecorder) MuteNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MuteNotification", reflect.TypeOf((*MockStore)(nil).MuteNotification), ctx, userID, githubID)
}

// RemoveTagAssignment mocks base method.
func (m *MockStore) RemoveTagAssignment(ctx context.Context, userID string, arg db.RemoveTagAssignmentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagAssignment", ctx, userID, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagAssignment indicates an expected call of RemoveTagAssignment.
func (mr *MockStoreMockRecorder) RemoveTagAssignment(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagAssignment", reflect.TypeOf((*MockStore)(nil).RemoveTagAssignment), ctx, userID, arg)
}

// SnoozeNotification mocks base method.
func (m *MockStore) SnoozeNotification(ctx context.Context, userID string, arg db.SnoozeNotificationParams) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnoozeNotification", ctx, userID, arg)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnoozeNotification indicates an expected call of SnoozeNotification.
func (mr *MockStoreMockRecorder) SnoozeNotification(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnoozeNotification", reflect.TypeOf((*MockStore)(nil).SnoozeNotification), ctx, userID, arg)
}

// StarNotification mocks base method.
func (m *MockStore) StarNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StarNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StarNotification indicates an expected call of StarNotification.
func (mr *MockStoreMockRecorder) StarNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StarNotification", reflect.TypeOf((*MockStore)(nil).StarNotification), ctx, userID, githubID)
}

// UnarchiveNotification mocks base method.
func (m *MockStore) UnarchiveNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnarchiveNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnarchiveNotification indicates an expected call of UnarchiveNotification.
func (mr *MockStoreMockRecorder) UnarchiveNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnarchiveNotification", reflect.TypeOf((*MockStore)(nil).UnarchiveNotification), ctx, userID, githubID)
}

// UnmuteNotification mocks base method.
func (m *MockStore) UnmuteNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmuteNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmuteNotification indicates an expected call of UnmuteNotification.
func (mr *MockStoreMockRecorder) UnmuteNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmuteNotification", reflect.TypeOf((*MockStore)(nil).UnmuteNotification), ctx, userID, githubID)
}

// UnsnoozeNotification mocks base method.
func (m *MockStore) UnsnoozeNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsnoozeNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsnoozeNotification indicates an expected call of UnsnoozeNotification.
func (mr *MockStoreMockRecorder) UnsnoozeNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsnoozeNotification", reflect.TypeOf((*MockStore)(nil).UnsnoozeNotification), ctx, userID, githubID)
}

// UnstarNotification mocks base method.
func (m *MockStore) UnstarNotification(ctx context.Context, userID, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnstarNotification", ctx, userID, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnstarNotification indicates an expected call of UnstarNotification.
func (mr *MockStoreMockRecorder) UnstarNotification(ctx, userID, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnstarNotification", reflect.TypeOf((*MockStore)(nil).UnstarNotification), ctx, userID, githubID)
}

// UpdateNotificationSubject mocks base method.
func (m *MockStore) UpdateNotificationSubject(ctx context.Context, userID string, arg db.UpdateNotificationSubjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationSubject", ctx, userID, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationSubject indicates an expected call of UpdateNotificationSubject.
func (mr *MockStoreMockRecorder) UpdateNotificationSubject(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationSubject", reflect.TypeOf((*MockStore)(nil).UpdateNotificationSubject), ctx, userID, arg)
}

// UpdateRule mocks base method.
func (m *MockStore) UpdateRule(ctx context.Context, userID string, arg db.UpdateRuleParams) (db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, userID, arg)
	ret0, _ := ret[0].(db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockStoreMockRecorder) UpdateRule(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockStore)(nil).UpdateRule), ctx, userID, arg)
}

// UpdateRuleOrder mocks base method.
func (m *MockStore) UpdateRuleOrder(ctx context.Context, userID string, arg db.UpdateRuleOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRuleOrder", ctx, userID, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRuleOrder indicates an expected call of UpdateRuleOrder.
func (mr *MockStoreMockRecorder) UpdateRuleOrder(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRuleOrder", reflect.TypeOf((*MockStore)(nil).UpdateRuleOrder), ctx, userID, arg)
}

// UpdateTag mocks base method.
func (m *MockStore) UpdateTag(ctx context.Context, userID string, arg db.UpdateTagParams) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", ctx, userID, arg)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockStoreMockRecorder) UpdateTag(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockStore)(nil).UpdateTag), ctx, userID, arg)
}

// UpdateTagDisplayOrder mocks base method.
func (m *MockStore) UpdateTagDisplayOrder(ctx context.Context, userID string, arg db.UpdateTagDisplayOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTagDisplayOrder", ctx, userID, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTagDisplayOrder indicates an expected call of UpdateTagDisplayOrder.
func (mr *MockStoreMockRecorder) UpdateTagDisplayOrder(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTagDisplayOrder", reflect.TypeOf((*MockStore)(nil).UpdateTagDisplayOrder), ctx, userID, arg)
}

// UpdateUserGitHubIdentity mocks base method.
func (m *MockStore) UpdateUserGitHubIdentity(ctx context.Context, arg db.UpdateUserGitHubIdentityParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGitHubIdentity", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserGitHubIdentity indicates an expected call of UpdateUserGitHubIdentity.
func (mr *MockStoreMockRecorder) UpdateUserGitHubIdentity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGitHubIdentity", reflect.TypeOf((*MockStore)(nil).UpdateUserGitHubIdentity), ctx, arg)
}

// UpdateUserGitHubToken mocks base method.
func (m *MockStore) UpdateUserGitHubToken(ctx context.Context, githubTokenEncrypted sql.NullString) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGitHubToken", ctx, githubTokenEncrypted)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserGitHubToken indicates an expected call of UpdateUserGitHubToken.
func (mr *MockStoreMockRecorder) UpdateUserGitHubToken(ctx, githubTokenEncrypted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGitHubToken", reflect.TypeOf((*MockStore)(nil).UpdateUserGitHubToken), ctx, githubTokenEncrypted)
}

// UpdateUserMutedUntil mocks base method.
func (m *MockStore) UpdateUserMutedUntil(ctx context.Context, mutedUntil sql.NullTime) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserMutedUntil", ctx, mutedUntil)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserMutedUntil indicates an expected call of UpdateUserMutedUntil.
func (mr *MockStoreMockRecorder) UpdateUserMutedUntil(ctx, mutedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserMutedUntil", reflect.TypeOf((*MockStore)(nil).UpdateUserMutedUntil), ctx, mutedUntil)
}

// UpdateUserRetentionSettings mocks base method.
func (m *MockStore) UpdateUserRetentionSettings(ctx context.Context, retentionSettings sql.NullString) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRetentionSettings", ctx, retentionSettings)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRetentionSettings indicates an expected call of UpdateUserRetentionSettings.
func (mr *MockStoreMockRecorder) UpdateUserRetentionSettings(ctx, retentionSettings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRetentionSettings", reflect.TypeOf((*MockStore)(nil).UpdateUserRetentionSettings), ctx, retentionSettings)
}

// UpdateUserSyncSettings mocks base method.
func (m *MockStore) UpdateUserSyncSettings(ctx context.Context, syncSettings db.NullRawMessage) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserSyncSettings", ctx, syncSettings)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserSyncSettings indicates an expected call of UpdateUserSyncSettings.
func (mr *MockStoreMockRecorder) UpdateUserSyncSettings(ctx, syncSettings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserSyncSettings", reflect.TypeOf((*MockStore)(nil).UpdateUserSyncSettings), ctx, syncSettings)
}

// UpdateUserUpdateSettings mocks base method.
func (m *MockStore) UpdateUserUpdateSettings(ctx context.Context, updateSettings db.NullRawMessage) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserUpdateSettings", ctx, updateSettings)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserUpdateSettings indicates an expected call of UpdateUserUpdateSettings.
func (mr *MockStoreMockRecorder) UpdateUserUpdateSettings(ctx, updateSettings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserUpdateSettings", reflect.TypeOf((*MockStore)(nil).UpdateUserUpdateSettings), ctx, updateSettings)
}

// UpdateView mocks base method.
func (m *MockStore) UpdateView(ctx context.Context, userID string, arg db.UpdateViewParams) (db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateView", ctx, userID, arg)
	ret0, _ := ret[0].(db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateView indicates an expected call of UpdateView.
func (mr *MockStoreMockRecorder) UpdateView(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateView", reflect.TypeOf((*MockStore)(nil).UpdateView), ctx, userID, arg)
}

// UpdateViewOrder mocks base method.
func (m *MockStore) UpdateViewOrder(ctx context.Context, userID string, arg db.UpdateViewOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateViewOrder", ctx, userID, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateViewOrder indicates an expected call of UpdateViewOrder.
func (mr *MockStoreMockRecorder) UpdateViewOrder(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateViewOrder", reflect.TypeOf((*MockStore)(nil).UpdateViewOrder), ctx, userID, arg)
}

// UpsertNotification mocks base method.
func (m *MockStore) UpsertNotification(ctx context.Context, userID string, arg db.UpsertNotificationParams) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotification", ctx, userID, arg)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertNotification indicates an expected call of UpsertNotification.
func (mr *MockStoreMockRecorder) UpsertNotification(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotification", reflect.TypeOf((*MockStore)(nil).UpsertNotification), ctx, userID, arg)
}

// UpsertPullRequest mocks base method.
func (m *MockStore) UpsertPullRequest(ctx context.Context, userID string, arg db.UpsertPullRequestParams) (db.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPullRequest", ctx, userID, arg)
	ret0, _ := ret[0].(db.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPullRequest indicates an expected call of UpsertPullRequest.
func (mr *MockStoreMockRecorder) UpsertPullRequest(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPullRequest", reflect.TypeOf((*MockStore)(nil).UpsertPullRequest), ctx, userID, arg)
}

// UpsertRepository mocks base method.
func (m *MockStore) UpsertRepository(ctx context.Context, userID string, arg db.UpsertRepositoryParams) (db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRepository", ctx, userID, arg)
	ret0, _ := ret[0].(db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRepository indicates an expected call of UpsertRepository.
func (mr *MockStoreMockRecorder) UpsertRepository(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRepository", reflect.TypeOf((*MockStore)(nil).UpsertRepository), ctx, userID, arg)
}

// UpsertSyncState mocks base method.
func (m *MockStore) UpsertSyncState(ctx context.Context, userID string, arg db.UpsertSyncStateParams) (db.UpsertSyncStateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSyncState", ctx, userID, arg)
	ret0, _ := ret[0].(db.UpsertSyncStateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSyncState indicates an expected call of UpsertSyncState.
func (mr *MockStoreMockRecorder) UpsertSyncState(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSyncState", reflect.TypeOf((*MockStore)(nil).UpsertSyncState), ctx, userID, arg)
}

// UpsertTag mocks base method.
func (m *MockStore) UpsertTag(ctx context.Context, userID string, arg db.UpsertTagParams) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTag", ctx, userID, arg)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTag indicates an expected call of UpsertTag.
func (mr *MockStoreMockRecorder) UpsertTag(ctx, userID, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTag", reflect.TypeOf((*MockStore)(nil).UpsertTag), ctx, userID, arg)
}
