// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrichment.sql

package sqlite

import (
	"context"
	"database/sql"
)

const listNotificationsForEnrichment = `-- name: ListNotificationsForEnrichment :many
SELECT id, github_id, subject_type, subject_url, subject_raw, enrichment_version
FROM notifications
WHERE user_id = ?
  AND enrichment_version < ?2
  AND subject_raw IS NOT NULL
ORDER BY effective_sort_date DESC
LIMIT ?3
`

type ListNotificationsForEnrichmentParams struct {
	UserID        string
	TargetVersion int64
	BatchLimit    int64
}

type ListNotificationsForEnrichmentRow struct {
	ID                int64
	GithubID          string
	SubjectType       string
	SubjectUrl        sql.NullString
	SubjectRaw        sql.NullString
	EnrichmentVersion int64
}

// Returns notifications that need enrichment (version < target).
// Scoped by subject_type when provided, otherwise all types.
func (q *Queries) ListNotificationsForEnrichment(ctx context.Context, arg ListNotificationsForEnrichmentParams) ([]ListNotificationsForEnrichmentRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForEnrichment, arg.UserID, arg.TargetVersion, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsForEnrichmentRow
	for rows.Next() {
		var i ListNotificationsForEnrichmentRow
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.SubjectType,
			&i.SubjectUrl,
			&i.SubjectRaw,
			&i.EnrichmentVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationEnrichmentVersion = `-- name: UpdateNotificationEnrichmentVersion :exec
UPDATE notifications SET enrichment_version = ? WHERE id = ?
`

type UpdateNotificationEnrichmentVersionParams struct {
	EnrichmentVersion int64
	ID                int64
}

func (q *Queries) UpdateNotificationEnrichmentVersion(ctx context.Context, arg UpdateNotificationEnrichmentVersionParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationEnrichmentVersion, arg.EnrichmentVersion, arg.ID)
	return err
}
