// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_data.sql

package sqlite

import (
	"context"
)

const deleteAllGitHubData = `-- name: DeleteAllGitHubData :exec
DELETE FROM tag_assignments WHERE user_id = ?
`

// Delete all GitHub data for a user (notifications, pull requests, repositories, sync state, tag assignments)
// Preserves: tags, views, rules, users
func (q *Queries) DeleteAllGitHubData(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllGitHubData, userID)
	return err
}
