// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type Job struct {
	ID          int64
	Queue       string
	Payload     string
	Status      string
	Attempts    int64
	MaxAttempts int64
	CreatedAt   string
	UpdatedAt   string
	ScheduledAt string
	StartedAt   sql.NullString
	CompletedAt sql.NullString
	LastError   sql.NullString
}

type Notification struct {
	ID                      int64
	UserID                  string
	GithubID                string
	RepositoryID            int64
	PullRequestID           sql.NullInt64
	SubjectType             string
	SubjectTitle            string
	SubjectUrl              sql.NullString
	SubjectLatestCommentUrl sql.NullString
	Reason                  sql.NullString
	Archived                int64
	GithubUnread            sql.NullInt64
	GithubUpdatedAt         sql.NullString
	GithubLastReadAt        sql.NullString
	GithubUrl               sql.NullString
	GithubSubscriptionUrl   sql.NullString
	ImportedAt              string
	Payload                 sql.NullString
	SubjectRaw              sql.NullString
	SubjectFetchedAt        sql.NullString
	AuthorLogin             sql.NullString
	AuthorID                sql.NullInt64
	IsRead                  int64
	Muted                   int64
	SnoozedUntil            sql.NullString
	EffectiveSortDate       string
	SnoozedAt               sql.NullString
	Starred                 int64
	Filtered                int64
	SubjectNumber           sql.NullInt64
	SubjectState            sql.NullString
	SubjectMerged           sql.NullInt64
	SubjectStateReason      sql.NullString
}

type PullRequest struct {
	ID           int64
	UserID       string
	RepositoryID int64
	GithubID     sql.NullInt64
	NodeID       sql.NullString
	Number       int64
	Title        sql.NullString
	State        sql.NullString
	Draft        sql.NullInt64
	Merged       sql.NullInt64
	AuthorLogin  sql.NullString
	AuthorID     sql.NullInt64
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
	ClosedAt     sql.NullString
	MergedAt     sql.NullString
	Raw          sql.NullString
}

type Repository struct {
	ID             int64
	UserID         string
	GithubID       sql.NullInt64
	NodeID         sql.NullString
	Name           string
	FullName       string
	OwnerLogin     sql.NullString
	OwnerID        sql.NullInt64
	Private        sql.NullInt64
	Description    sql.NullString
	HtmlUrl        sql.NullString
	Fork           sql.NullInt64
	Visibility     sql.NullString
	DefaultBranch  sql.NullString
	Archived       sql.NullInt64
	Disabled       sql.NullInt64
	PushedAt       sql.NullString
	CreatedAt      sql.NullString
	UpdatedAt      sql.NullString
	Raw            sql.NullString
	OwnerAvatarUrl sql.NullString
	OwnerHtmlUrl   sql.NullString
}

type Rule struct {
	ID           string
	UserID       string
	Name         string
	Description  sql.NullString
	Query        sql.NullString
	Enabled      int64
	Actions      string
	DisplayOrder int64
	CreatedAt    string
	UpdatedAt    string
	ViewID       sql.NullString
}

type SyncState struct {
	ID                         int64
	UserID                     string
	LastSuccessfulPoll         sql.NullString
	LastNotificationEtag       sql.NullString
	CreatedAt                  string
	UpdatedAt                  string
	LatestNotificationAt       sql.NullString
	InitialSyncCompletedAt     sql.NullString
	OldestNotificationSyncedAt sql.NullString
}

type Tag struct {
	ID           string
	UserID       string
	Name         string
	Color        sql.NullString
	Description  sql.NullString
	CreatedAt    string
	DisplayOrder int64
	Slug         string
}

type TagAssignment struct {
	ID         string
	UserID     string
	TagID      string
	EntityType string
	EntityID   int64
	CreatedAt  string
}

type User struct {
	ID                   int64
	GithubUserID         sql.NullString
	GithubUsername       sql.NullString
	GithubTokenEncrypted sql.NullString
	CreatedAt            string
	UpdatedAt            string
	SyncSettings         sql.NullString
	RetentionSettings    sql.NullString
	MutedUntil           sql.NullString
	UpdateSettings       sql.NullString
}

type View struct {
	ID           string
	UserID       string
	Name         string
	Description  sql.NullString
	IsDefault    int64
	CreatedAt    string
	Icon         sql.NullString
	Slug         string
	Query        sql.NullString
	DisplayOrder int64
}
