// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_metadata.sql

package sqlite

import (
	"context"
	"database/sql"
)

const deleteNotificationAssignees = `-- name: DeleteNotificationAssignees :exec
DELETE FROM notification_assignees WHERE notification_id = ?
`

func (q *Queries) DeleteNotificationAssignees(ctx context.Context, notificationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationAssignees, notificationID)
	return err
}

const deleteNotificationLabels = `-- name: DeleteNotificationLabels :exec
DELETE FROM notification_labels WHERE notification_id = ?
`

func (q *Queries) DeleteNotificationLabels(ctx context.Context, notificationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationLabels, notificationID)
	return err
}

const deleteNotificationReviewers = `-- name: DeleteNotificationReviewers :exec
DELETE FROM notification_reviewers WHERE notification_id = ?
`

func (q *Queries) DeleteNotificationReviewers(ctx context.Context, notificationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationReviewers, notificationID)
	return err
}

const deleteNotificationTeamReviewers = `-- name: DeleteNotificationTeamReviewers :exec
DELETE FROM notification_team_reviewers WHERE notification_id = ?
`

func (q *Queries) DeleteNotificationTeamReviewers(ctx context.Context, notificationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationTeamReviewers, notificationID)
	return err
}

const getNotificationAssignees = `-- name: GetNotificationAssignees :many
SELECT login, github_id, avatar_url FROM notification_assignees WHERE notification_id = ?
`

type GetNotificationAssigneesRow struct {
	Login     string
	GithubID  sql.NullInt64
	AvatarUrl sql.NullString
}

func (q *Queries) GetNotificationAssignees(ctx context.Context, notificationID int64) ([]GetNotificationAssigneesRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationAssignees, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationAssigneesRow
	for rows.Next() {
		var i GetNotificationAssigneesRow
		if err := rows.Scan(&i.Login, &i.GithubID, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationLabels = `-- name: GetNotificationLabels :many
SELECT name, color FROM notification_labels WHERE notification_id = ?
`

type GetNotificationLabelsRow struct {
	Name  string
	Color sql.NullString
}

func (q *Queries) GetNotificationLabels(ctx context.Context, notificationID int64) ([]GetNotificationLabelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationLabels, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationLabelsRow
	for rows.Next() {
		var i GetNotificationLabelsRow
		if err := rows.Scan(&i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationReviewers = `-- name: GetNotificationReviewers :many
SELECT login, github_id, status, avatar_url FROM notification_reviewers WHERE notification_id = ?
`

type GetNotificationReviewersRow struct {
	Login     string
	GithubID  sql.NullInt64
	Status    string
	AvatarUrl sql.NullString
}

func (q *Queries) GetNotificationReviewers(ctx context.Context, notificationID int64) ([]GetNotificationReviewersRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationReviewers, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationReviewersRow
	for rows.Next() {
		var i GetNotificationReviewersRow
		if err := rows.Scan(
			&i.Login,
			&i.GithubID,
			&i.Status,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationTeamReviewers = `-- name: GetNotificationTeamReviewers :many
SELECT slug, github_id FROM notification_team_reviewers WHERE notification_id = ?
`

type GetNotificationTeamReviewersRow struct {
	Slug     string
	GithubID sql.NullInt64
}

func (q *Queries) GetNotificationTeamReviewers(ctx context.Context, notificationID int64) ([]GetNotificationTeamReviewersRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationTeamReviewers, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationTeamReviewersRow
	for rows.Next() {
		var i GetNotificationTeamReviewersRow
		if err := rows.Scan(&i.Slug, &i.GithubID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotificationAssignee = `-- name: InsertNotificationAssignee :exec
INSERT INTO notification_assignees (notification_id, login, github_id, avatar_url) VALUES (?, ?, ?, ?)
`

type InsertNotificationAssigneeParams struct {
	NotificationID int64
	Login          string
	GithubID       sql.NullInt64
	AvatarUrl      sql.NullString
}

func (q *Queries) InsertNotificationAssignee(ctx context.Context, arg InsertNotificationAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, insertNotificationAssignee,
		arg.NotificationID,
		arg.Login,
		arg.GithubID,
		arg.AvatarUrl,
	)
	return err
}

const insertNotificationLabel = `-- name: InsertNotificationLabel :exec
INSERT INTO notification_labels (notification_id, name, color) VALUES (?, ?, ?)
`

type InsertNotificationLabelParams struct {
	NotificationID int64
	Name           string
	Color          sql.NullString
}

func (q *Queries) InsertNotificationLabel(ctx context.Context, arg InsertNotificationLabelParams) error {
	_, err := q.db.ExecContext(ctx, insertNotificationLabel, arg.NotificationID, arg.Name, arg.Color)
	return err
}

const insertNotificationReviewer = `-- name: InsertNotificationReviewer :exec
INSERT INTO notification_reviewers (notification_id, login, github_id, status, avatar_url) VALUES (?, ?, ?, ?, ?)
`

type InsertNotificationReviewerParams struct {
	NotificationID int64
	Login          string
	GithubID       sql.NullInt64
	Status         string
	AvatarUrl      sql.NullString
}

func (q *Queries) InsertNotificationReviewer(ctx context.Context, arg InsertNotificationReviewerParams) error {
	_, err := q.db.ExecContext(ctx, insertNotificationReviewer,
		arg.NotificationID,
		arg.Login,
		arg.GithubID,
		arg.Status,
		arg.AvatarUrl,
	)
	return err
}

const insertNotificationTeamReviewer = `-- name: InsertNotificationTeamReviewer :exec
INSERT INTO notification_team_reviewers (notification_id, slug, github_id) VALUES (?, ?, ?)
`

type InsertNotificationTeamReviewerParams struct {
	NotificationID int64
	Slug           string
	GithubID       sql.NullInt64
}

func (q *Queries) InsertNotificationTeamReviewer(ctx context.Context, arg InsertNotificationTeamReviewerParams) error {
	_, err := q.db.ExecContext(ctx, insertNotificationTeamReviewer, arg.NotificationID, arg.Slug, arg.GithubID)
	return err
}

const updateNotificationDraft = `-- name: UpdateNotificationDraft :exec
UPDATE notifications SET subject_draft = ? WHERE id = ?
`

type UpdateNotificationDraftParams struct {
	SubjectDraft sql.NullInt64
	ID           int64
}

func (q *Queries) UpdateNotificationDraft(ctx context.Context, arg UpdateNotificationDraftParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationDraft, arg.SubjectDraft, arg.ID)
	return err
}
