// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (user_id, name, description, query, view_id, enabled, actions, display_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, user_id, name, description, "query", enabled, actions, display_order, created_at, updated_at, view_id
`

type CreateRuleParams struct {
	UserID       string
	Name         string
	Description  sql.NullString
	Query        sql.NullString
	ViewID       sql.NullString
	Enabled      int64
	Actions      string
	DisplayOrder int64
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, createRule,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.ViewID,
		arg.Enabled,
		arg.Actions,
		arg.DisplayOrder,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Enabled,
		&i.Actions,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewID,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE user_id = ? AND id = ?
`

type DeleteRuleParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRule, arg.UserID, arg.ID)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, user_id, name, description, "query", enabled, actions, display_order, created_at, updated_at, view_id FROM rules WHERE user_id = ? AND id = ?
`

type GetRuleParams struct {
	UserID string
	ID     string
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, getRule, arg.UserID, arg.ID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Enabled,
		&i.Actions,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewID,
	)
	return i, err
}

const getRulesByViewID = `-- name: GetRulesByViewID :many
SELECT id, user_id, name, description, "query", enabled, actions, display_order, created_at, updated_at, view_id FROM rules WHERE user_id = ? AND view_id = ? ORDER BY display_order
`

type GetRulesByViewIDParams struct {
	UserID string
	ViewID sql.NullString
}

func (q *Queries) GetRulesByViewID(ctx context.Context, arg GetRulesByViewIDParams) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, getRulesByViewID, arg.UserID, arg.ViewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Enabled,
			&i.Actions,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledRulesOrdered = `-- name: ListEnabledRulesOrdered :many
SELECT id, user_id, name, description, "query", enabled, actions, display_order, created_at, updated_at, view_id FROM rules WHERE user_id = ? AND enabled = 1 ORDER BY display_order
`

func (q *Queries) ListEnabledRulesOrdered(ctx context.Context, userID string) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRulesOrdered, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Enabled,
			&i.Actions,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, user_id, name, description, "query", enabled, actions, display_order, created_at, updated_at, view_id FROM rules WHERE user_id = ? ORDER BY display_order, name
`

func (q *Queries) ListRules(ctx context.Context, userID string) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Enabled,
			&i.Actions,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules SET
    name = COALESCE(?, name),
    description = COALESCE(?, description),
    query = COALESCE(?, query),
    view_id = ?,
    enabled = COALESCE(?, enabled),
    actions = COALESCE(?, actions),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE user_id = ? AND id = ?
RETURNING id, user_id, name, description, "query", enabled, actions, display_order, created_at, updated_at, view_id
`

type UpdateRuleParams struct {
	Name        string
	Description sql.NullString
	Query       sql.NullString
	ViewID      sql.NullString
	Enabled     int64
	Actions     string
	UserID      string
	ID          string
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, updateRule,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.ViewID,
		arg.Enabled,
		arg.Actions,
		arg.UserID,
		arg.ID,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Enabled,
		&i.Actions,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewID,
	)
	return i, err
}

const updateRuleOrder = `-- name: UpdateRuleOrder :exec
UPDATE rules SET display_order = ? WHERE user_id = ? AND id = ?
`

type UpdateRuleOrderParams struct {
	DisplayOrder int64
	UserID       string
	ID           string
}

func (q *Queries) UpdateRuleOrder(ctx context.Context, arg UpdateRuleOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateRuleOrder, arg.DisplayOrder, arg.UserID, arg.ID)
	return err
}
