// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_state.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getSyncState = `-- name: GetSyncState :one
SELECT id, user_id, last_successful_poll, last_notification_etag, created_at, updated_at, latest_notification_at, initial_sync_completed_at, oldest_notification_synced_at FROM sync_state WHERE user_id = ?
`

func (q *Queries) GetSyncState(ctx context.Context, userID string) (SyncState, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, userID)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastSuccessfulPoll,
		&i.LastNotificationEtag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestNotificationAt,
		&i.InitialSyncCompletedAt,
		&i.OldestNotificationSyncedAt,
	)
	return i, err
}

const upsertSyncState = `-- name: UpsertSyncState :one
INSERT INTO sync_state (
    user_id, last_successful_poll, last_notification_etag, 
    latest_notification_at, initial_sync_completed_at, oldest_notification_synced_at,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
)
ON CONFLICT(user_id) DO UPDATE SET
    last_successful_poll = COALESCE(excluded.last_successful_poll, sync_state.last_successful_poll),
    last_notification_etag = COALESCE(excluded.last_notification_etag, sync_state.last_notification_etag),
    latest_notification_at = COALESCE(excluded.latest_notification_at, sync_state.latest_notification_at),
    initial_sync_completed_at = COALESCE(excluded.initial_sync_completed_at, sync_state.initial_sync_completed_at),
    -- The oldest-synced marker only ever moves backwards: a sync window that ends later
    -- than the current oldest (e.g. a re-sync of the last 30 days) must not advance it.
    oldest_notification_synced_at = CASE
        WHEN excluded.oldest_notification_synced_at IS NULL THEN sync_state.oldest_notification_synced_at
        WHEN sync_state.oldest_notification_synced_at IS NULL THEN excluded.oldest_notification_synced_at
        ELSE MIN(excluded.oldest_notification_synced_at, sync_state.oldest_notification_synced_at)
    END,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, user_id, last_successful_poll, last_notification_etag, created_at, updated_at, latest_notification_at, initial_sync_completed_at, oldest_notification_synced_at
`

type UpsertSyncStateParams struct {
	UserID                     string
	LastSuccessfulPoll         sql.NullString
	LastNotificationEtag       sql.NullString
	LatestNotificationAt       sql.NullString
	InitialSyncCompletedAt     sql.NullString
	OldestNotificationSyncedAt sql.NullString
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (SyncState, error) {
	row := q.db.QueryRowContext(ctx, upsertSyncState,
		arg.UserID,
		arg.LastSuccessfulPoll,
		arg.LastNotificationEtag,
		arg.LatestNotificationAt,
		arg.InitialSyncCompletedAt,
		arg.OldestNotificationSyncedAt,
	)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastSuccessfulPoll,
		&i.LastNotificationEtag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestNotificationAt,
		&i.InitialSyncCompletedAt,
		&i.OldestNotificationSyncedAt,
	)
	return i, err
}
