// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlite

import (
	"context"
	"database/sql"
)

const assignTagToEntity = `-- name: AssignTagToEntity :one
INSERT INTO tag_assignments (user_id, tag_id, entity_type, entity_id, created_at)
VALUES (?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(user_id, tag_id, entity_type, entity_id) DO UPDATE SET entity_type = excluded.entity_type
RETURNING id, user_id, tag_id, entity_type, entity_id, created_at
`

type AssignTagToEntityParams struct {
	UserID     string
	TagID      string
	EntityType string
	EntityID   int64
}

func (q *Queries) AssignTagToEntity(ctx context.Context, arg AssignTagToEntityParams) (TagAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignTagToEntity,
		arg.UserID,
		arg.TagID,
		arg.EntityType,
		arg.EntityID,
	)
	var i TagAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TagID,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE user_id = ? AND id = ?
`

type DeleteTagParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.UserID, arg.ID)
	return err
}

const getNotificationTagIDs = `-- name: GetNotificationTagIDs :many
SELECT tag_id FROM tag_assignments WHERE user_id = ? AND entity_type = 'notification' AND entity_id = ?
`

type GetNotificationTagIDsParams struct {
	UserID   string
	EntityID int64
}

func (q *Queries) GetNotificationTagIDs(ctx context.Context, arg GetNotificationTagIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationTagIDs, arg.UserID, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, user_id, name, color, description, created_at, display_order, slug FROM tags WHERE user_id = ? AND id = ?
`

type GetTagParams struct {
	UserID string
	ID     string
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, arg.UserID, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, user_id, name, color, description, created_at, display_order, slug FROM tags WHERE user_id = ? AND name = ?
`

type GetTagByNameParams struct {
	UserID string
	Name   string
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, user_id, name, color, description, created_at, display_order, slug FROM tags WHERE user_id = ? ORDER BY display_order, name
`

func (q *Queries) ListAllTags(ctx context.Context, userID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.DisplayOrder,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForEntity = `-- name: ListTagsForEntity :many
SELECT t.id, t.user_id, t.name, t.color, t.description, t.created_at, t.display_order, t.slug FROM tags t
JOIN tag_assignments ta ON t.id = ta.tag_id
WHERE t.user_id = ? AND ta.entity_type = ? AND ta.entity_id = ?
ORDER BY t.display_order, t.name
`

type ListTagsForEntityParams struct {
	UserID     string
	EntityType string
	EntityID   int64
}

func (q *Queries) ListTagsForEntity(ctx context.Context, arg ListTagsForEntityParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForEntity, arg.UserID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.DisplayOrder,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagAssignment = `-- name: RemoveTagAssignment :exec
DELETE FROM tag_assignments 
WHERE user_id = ? AND tag_id = ? AND entity_type = ? AND entity_id = ?
`

type RemoveTagAssignmentParams struct {
	UserID     string
	TagID      string
	EntityType string
	EntityID   int64
}

func (q *Queries) RemoveTagAssignment(ctx context.Context, arg RemoveTagAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, removeTagAssignment,
		arg.UserID,
		arg.TagID,
		arg.EntityType,
		arg.EntityID,
	)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET
    name = COALESCE(?, name),
    slug = COALESCE(?, slug),
    color = COALESCE(?, color),
    description = COALESCE(?, description)
WHERE user_id = ? AND id = ?
RETURNING id, user_id, name, color, description, created_at, display_order, slug
`

type UpdateTagParams struct {
	Name        string
	Slug        string
	Color       sql.NullString
	Description sql.NullString
	UserID      string
	ID          string
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.Description,
		arg.UserID,
		arg.ID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}

const updateTagDisplayOrder = `-- name: UpdateTagDisplayOrder :exec
UPDATE tags SET display_order = ? WHERE user_id = ? AND id = ?
`

type UpdateTagDisplayOrderParams struct {
	DisplayOrder int64
	UserID       string
	ID           string
}

func (q *Queries) UpdateTagDisplayOrder(ctx context.Context, arg UpdateTagDisplayOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTagDisplayOrder, arg.DisplayOrder, arg.UserID, arg.ID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (user_id, name, slug, color, description, created_at, display_order)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), 0)
ON CONFLICT(user_id, name) DO UPDATE SET
    slug = excluded.slug,
    color = excluded.color,
    description = excluded.description
RETURNING id, user_id, name, color, description, created_at, display_order, slug
`

type UpsertTagParams struct {
	UserID      string
	Name        string
	Slug        string
	Color       sql.NullString
	Description sql.NullString
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.Description,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}
