// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlite

import (
	"context"
	"database/sql"
)

const clearUserGitHubToken = `-- name: ClearUserGitHubToken :one
UPDATE users SET 
    github_token_encrypted = NULL, 
    github_user_id = NULL,
    github_username = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') 
WHERE id = 1 RETURNING id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings
`

func (q *Queries) ClearUserGitHubToken(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, clearUserGitHubToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at)
VALUES (1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings
`

// Creates the single user record (id is always 1)
func (q *Queries) CreateUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings FROM users WHERE id = 1
`

func (q *Queries) GetUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}

const updateUserGitHubIdentity = `-- name: UpdateUserGitHubIdentity :one
UPDATE users SET 
    github_user_id = ?, 
    github_username = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') 
WHERE id = 1 RETURNING id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings
`

type UpdateUserGitHubIdentityParams struct {
	GithubUserID   sql.NullString
	GithubUsername sql.NullString
}

// Updates the GitHub identity (user ID and username from GitHub)
func (q *Queries) UpdateUserGitHubIdentity(ctx context.Context, arg UpdateUserGitHubIdentityParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserGitHubIdentity, arg.GithubUserID, arg.GithubUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}

const updateUserGitHubToken = `-- name: UpdateUserGitHubToken :one
UPDATE users SET github_token_encrypted = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 1 RETURNING id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings
`

func (q *Queries) UpdateUserGitHubToken(ctx context.Context, githubTokenEncrypted sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserGitHubToken, githubTokenEncrypted)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}

const updateUserMutedUntil = `-- name: UpdateUserMutedUntil :one
UPDATE users SET muted_until = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 1 RETURNING id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings
`

func (q *Queries) UpdateUserMutedUntil(ctx context.Context, mutedUntil sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserMutedUntil, mutedUntil)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}

const updateUserRetentionSettings = `-- name: UpdateUserRetentionSettings :one
UPDATE users SET retention_settings = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 1 RETURNING id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings
`

func (q *Queries) UpdateUserRetentionSettings(ctx context.Context, retentionSettings sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRetentionSettings, retentionSettings)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}

const updateUserSyncSettings = `-- name: UpdateUserSyncSettings :one
UPDATE users SET sync_settings = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 1 RETURNING id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings
`

func (q *Queries) UpdateUserSyncSettings(ctx context.Context, syncSettings sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserSyncSettings, syncSettings)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}

const updateUserUpdateSettings = `-- name: UpdateUserUpdateSettings :one
UPDATE users SET update_settings = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = 1 RETURNING id, github_user_id, github_username, github_token_encrypted, created_at, updated_at, sync_settings, retention_settings, muted_until, update_settings
`

func (q *Queries) UpdateUserUpdateSettings(ctx context.Context, updateSettings sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserUpdateSettings, updateSettings)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncSettings,
		&i.RetentionSettings,
		&i.MutedUntil,
		&i.UpdateSettings,
	)
	return i, err
}
