// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: view_repository_defaults.sql

package sqlite

import (
	"context"
)

const deleteViewRepositoryDefault = `-- name: DeleteViewRepositoryDefault :exec
DELETE FROM view_repository_defaults WHERE user_id = ? AND view_key = ?
`

type DeleteViewRepositoryDefaultParams struct {
	UserID  string
	ViewKey string
}

func (q *Queries) DeleteViewRepositoryDefault(ctx context.Context, arg DeleteViewRepositoryDefaultParams) error {
	_, err := q.db.ExecContext(ctx, deleteViewRepositoryDefault, arg.UserID, arg.ViewKey)
	return err
}

const getViewRepositoryDefault = `-- name: GetViewRepositoryDefault :one
SELECT user_id, view_key, repository_ids, updated_at FROM view_repository_defaults WHERE user_id = ? AND view_key = ?
`

type GetViewRepositoryDefaultParams struct {
	UserID  string
	ViewKey string
}

func (q *Queries) GetViewRepositoryDefault(ctx context.Context, arg GetViewRepositoryDefaultParams) (ViewRepositoryDefault, error) {
	row := q.db.QueryRowContext(ctx, getViewRepositoryDefault, arg.UserID, arg.ViewKey)
	var i ViewRepositoryDefault
	err := row.Scan(
		&i.UserID,
		&i.ViewKey,
		&i.RepositoryIds,
		&i.UpdatedAt,
	)
	return i, err
}

const listViewRepositoryDefaults = `-- name: ListViewRepositoryDefaults :many
SELECT user_id, view_key, repository_ids, updated_at FROM view_repository_defaults WHERE user_id = ?
`

func (q *Queries) ListViewRepositoryDefaults(ctx context.Context, userID string) ([]ViewRepositoryDefault, error) {
	rows, err := q.db.QueryContext(ctx, listViewRepositoryDefaults, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ViewRepositoryDefault
	for rows.Next() {
		var i ViewRepositoryDefault
		if err := rows.Scan(
			&i.UserID,
			&i.ViewKey,
			&i.RepositoryIds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertViewRepositoryDefault = `-- name: UpsertViewRepositoryDefault :exec
INSERT INTO view_repository_defaults (user_id, view_key, repository_ids, updated_at)
VALUES (?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(user_id, view_key) DO UPDATE SET
    repository_ids = excluded.repository_ids,
    updated_at = excluded.updated_at
`

type UpsertViewRepositoryDefaultParams struct {
	UserID        string
	ViewKey       string
	RepositoryIds string
}

func (q *Queries) UpsertViewRepositoryDefault(ctx context.Context, arg UpsertViewRepositoryDefaultParams) error {
	_, err := q.db.ExecContext(ctx, upsertViewRepositoryDefault, arg.UserID, arg.ViewKey, arg.RepositoryIds)
	return err
}
