// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createView = `-- name: CreateView :one
INSERT INTO views (user_id, name, slug, description, is_default, icon, query, display_order, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, user_id, name, description, is_default, created_at, icon, slug, "query", display_order
`

type CreateViewParams struct {
	UserID       string
	Name         string
	Slug         string
	Description  sql.NullString
	IsDefault    int64
	Icon         sql.NullString
	Query        sql.NullString
	DisplayOrder int64
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (View, error) {
	row := q.db.QueryRowContext(ctx, createView,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsDefault,
		arg.Icon,
		arg.Query,
		arg.DisplayOrder,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.Icon,
		&i.Slug,
		&i.Query,
		&i.DisplayOrder,
	)
	return i, err
}

const deleteView = `-- name: DeleteView :execrows
DELETE FROM views WHERE user_id = ? AND id = ?
`

type DeleteViewParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteView(ctx context.Context, arg DeleteViewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteView, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getView = `-- name: GetView :one
SELECT id, user_id, name, description, is_default, created_at, icon, slug, "query", display_order FROM views WHERE user_id = ? AND id = ?
`

type GetViewParams struct {
	UserID string
	ID     string
}

func (q *Queries) GetView(ctx context.Context, arg GetViewParams) (View, error) {
	row := q.db.QueryRowContext(ctx, getView, arg.UserID, arg.ID)
	var i View
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.Icon,
		&i.Slug,
		&i.Query,
		&i.DisplayOrder,
	)
	return i, err
}

const listViews = `-- name: ListViews :many
SELECT id, user_id, name, description, is_default, created_at, icon, slug, "query", display_order FROM views WHERE user_id = ? ORDER BY display_order, name
`

func (q *Queries) ListViews(ctx context.Context, userID string) ([]View, error) {
	rows, err := q.db.QueryContext(ctx, listViews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.CreatedAt,
			&i.Icon,
			&i.Slug,
			&i.Query,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateView = `-- name: UpdateView :one
UPDATE views SET
    name = COALESCE(?, name),
    slug = COALESCE(?, slug),
    description = COALESCE(?, description),
    icon = COALESCE(?, icon),
    query = COALESCE(?, query),
    is_default = COALESCE(?, is_default)
WHERE user_id = ? AND id = ?
RETURNING id, user_id, name, description, is_default, created_at, icon, slug, "query", display_order
`

type UpdateViewParams struct {
	Name        string
	Slug        string
	Description sql.NullString
	Icon        sql.NullString
	Query       sql.NullString
	IsDefault   int64
	UserID      string
	ID          string
}

func (q *Queries) UpdateView(ctx context.Context, arg UpdateViewParams) (View, error) {
	row := q.db.QueryRowContext(ctx, updateView,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.Query,
		arg.IsDefault,
		arg.UserID,
		arg.ID,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.Icon,
		&i.Slug,
		&i.Query,
		&i.DisplayOrder,
	)
	return i, err
}

const updateViewOrder = `-- name: UpdateViewOrder :exec
UPDATE views SET display_order = ? WHERE user_id = ? AND id = ?
`

type UpdateViewOrderParams struct {
	DisplayOrder int64
	UserID       string
	ID           string
}

func (q *Queries) UpdateViewOrder(ctx context.Context, arg UpdateViewOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateViewOrder, arg.DisplayOrder, arg.UserID, arg.ID)
	return err
}
