// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/repository/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/repository/service.go -destination=internal/core/repository/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/octobud-hq/octobud/backend/internal/db"
	models "github.com/octobud-hq/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryService is a mock of RepositoryService interface.
type MockRepositoryService struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryServiceMockRecorder
	isgomock struct{}
}

// MockRepositoryServiceMockRecorder is the mock recorder for MockRepositoryService.
type MockRepositoryServiceMockRecorder struct {
	mock *MockRepositoryService
}

// NewMockRepositoryService creates a new mock instance.
func NewMockRepositoryService(ctrl *gomock.Controller) *MockRepositoryService {
	mock := &MockRepositoryService{ctrl: ctrl}
	mock.recorder = &MockRepositoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryService) EXPECT() *MockRepositoryServiceMockRecorder {
	return m.recorder
}

// GetRepositoryByID mocks base method.
func (m *MockRepositoryService) GetRepositoryByID(ctx context.Context, userID string, id int64) (db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByID", ctx, userID, id)
	ret0, _ := ret[0].(db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByID indicates an expected call of GetRepositoryByID.
func (mr *MockRepositoryServiceMockRecorder) GetRepositoryByID(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByID", reflect.TypeOf((*MockRepositoryService)(nil).GetRepositoryByID), ctx, userID, id)
}

// ListRepositories mocks base method.
func (m *MockRepositoryService) ListRepositories(ctx context.Context, userID string) ([]models.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositories", ctx, userID)
	ret0, _ := ret[0].([]models.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockRepositoryServiceMockRecorder) ListRepositories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*MockRepositoryService)(nil).ListRepositories), ctx, userID)
}

// ListRepositoriesAsMap mocks base method.
func (m *MockRepositoryService) ListRepositoriesAsMap(ctx context.Context, userID string) (map[int64]db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositoriesAsMap", ctx, userID)
	ret0, _ := ret[0].(map[int64]db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositoriesAsMap indicates an expected call of ListRepositoriesAsMap.
func (mr *MockRepositoryServiceMockRecorder) ListRepositoriesAsMap(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositoriesAsMap", reflect.TypeOf((*MockRepositoryService)(nil).ListRepositoriesAsMap), ctx, userID)
}

// UpsertRepository mocks base method.
func (m *MockRepositoryService) UpsertRepository(ctx context.Context, userID string, params db.UpsertRepositoryParams) (db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRepository", ctx, userID, params)
	ret0, _ := ret[0].(db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRepository indicates an expected call of UpsertRepository.
func (mr *MockRepositoryServiceMockRecorder) UpsertRepository(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRepository", reflect.TypeOf((*MockRepositoryService)(nil).UpsertRepository), ctx, userID, params)
}
