// Code generated by MockGen. DO NOT EDIT.
// Source: internal/jobs/handlers/rule_matcher.go
//
// Generated by this command:
//
//	mockgen -source=internal/jobs/handlers/rule_matcher.go -destination=internal/jobs/mocks/mock_rule_matcher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/octobud-hq/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleMatcherInterface is a mock of RuleMatcherInterface interface.
type MockRuleMatcherInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRuleMatcherInterfaceMockRecorder
	isgomock struct{}
}

// MockRuleMatcherInterfaceMockRecorder is the mock recorder for MockRuleMatcherInterface.
type MockRuleMatcherInterfaceMockRecorder struct {
	mock *MockRuleMatcherInterface
}

// NewMockRuleMatcherInterface creates a new mock instance.
func NewMockRuleMatcherInterface(ctrl *gomock.Controller) *MockRuleMatcherInterface {
	mock := &MockRuleMatcherInterface{ctrl: ctrl}
	mock.recorder = &MockRuleMatcherInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleMatcherInterface) EXPECT() *MockRuleMatcherInterfaceMockRecorder {
	return m.recorder
}

// ApplyRuleActions mocks base method.
func (m *MockRuleMatcherInterface) ApplyRuleActions(ctx context.Context, userID, githubID string, actions models.RuleActions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyRuleActions", ctx, userID, githubID, actions)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyRuleActions indicates an expected call of ApplyRuleActions.
func (mr *MockRuleMatcherInterfaceMockRecorder) ApplyRuleActions(ctx, userID, githubID, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRuleActions", reflect.TypeOf((*MockRuleMatcherInterface)(nil).ApplyRuleActions), ctx, userID, githubID, actions)
}
