// Code generated by MockGen. DO NOT EDIT.
// Source: internal/jobs/scheduler.go
//
// Generated by this command:
//
//	mockgen -source=internal/jobs/scheduler.go -destination=internal/jobs/mocks/mock_scheduler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jobs "github.com/octobud-hq/octobud/backend/internal/jobs"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
	isgomock struct{}
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// EnqueueApplyRule mocks base method.
func (m *MockScheduler) EnqueueApplyRule(ctx context.Context, userID, ruleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueApplyRule", ctx, userID, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueApplyRule indicates an expected call of EnqueueApplyRule.
func (mr *MockSchedulerMockRecorder) EnqueueApplyRule(ctx, userID, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueApplyRule", reflect.TypeOf((*MockScheduler)(nil).EnqueueApplyRule), ctx, userID, ruleID)
}

// EnqueueProcessNotification mocks base method.
func (m *MockScheduler) EnqueueProcessNotification(ctx context.Context, userID string, notificationData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueProcessNotification", ctx, userID, notificationData)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueProcessNotification indicates an expected call of EnqueueProcessNotification.
func (mr *MockSchedulerMockRecorder) EnqueueProcessNotification(ctx, userID, notificationData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueProcessNotification", reflect.TypeOf((*MockScheduler)(nil).EnqueueProcessNotification), ctx, userID, notificationData)
}

// EnqueueSyncNotifications mocks base method.
func (m *MockScheduler) EnqueueSyncNotifications(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueSyncNotifications", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueSyncNotifications indicates an expected call of EnqueueSyncNotifications.
func (mr *MockSchedulerMockRecorder) EnqueueSyncNotifications(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueSyncNotifications", reflect.TypeOf((*MockScheduler)(nil).EnqueueSyncNotifications), ctx, userID)
}

// EnqueueSyncOlder mocks base method.
func (m *MockScheduler) EnqueueSyncOlder(ctx context.Context, args jobs.SyncOlderNotificationsArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueSyncOlder", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueSyncOlder indicates an expected call of EnqueueSyncOlder.
func (mr *MockSchedulerMockRecorder) EnqueueSyncOlder(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueSyncOlder", reflect.TypeOf((*MockScheduler)(nil).EnqueueSyncOlder), ctx, args)
}

// Start mocks base method.
func (m *MockScheduler) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockSchedulerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockScheduler)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockScheduler) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSchedulerMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockScheduler)(nil).Stop), ctx)
}

// MockJobHandler is a mock of JobHandler interface.
type MockJobHandler struct {
	ctrl     *gomock.Controller
	recorder *MockJobHandlerMockRecorder
	isgomock struct{}
}

// MockJobHandlerMockRecorder is the mock recorder for MockJobHandler.
type MockJobHandlerMockRecorder struct {
	mock *MockJobHandler
}

// NewMockJobHandler creates a new mock instance.
func NewMockJobHandler(ctrl *gomock.Controller) *MockJobHandler {
	mock := &MockJobHandler{ctrl: ctrl}
	mock.recorder = &MockJobHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobHandler) EXPECT() *MockJobHandlerMockRecorder {
	return m.recorder
}

// HandleApplyRule mocks base method.
func (m *MockJobHandler) HandleApplyRule(ctx context.Context, userID, ruleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleApplyRule", ctx, userID, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleApplyRule indicates an expected call of HandleApplyRule.
func (mr *MockJobHandlerMockRecorder) HandleApplyRule(ctx, userID, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleApplyRule", reflect.TypeOf((*MockJobHandler)(nil).HandleApplyRule), ctx, userID, ruleID)
}

// HandleProcessNotification mocks base method.
func (m *MockJobHandler) HandleProcessNotification(ctx context.Context, userID string, notificationData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleProcessNotification", ctx, userID, notificationData)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleProcessNotification indicates an expected call of HandleProcessNotification.
func (mr *MockJobHandlerMockRecorder) HandleProcessNotification(ctx, userID, notificationData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProcessNotification", reflect.TypeOf((*MockJobHandler)(nil).HandleProcessNotification), ctx, userID, notificationData)
}

// HandleSyncNotifications mocks base method.
func (m *MockJobHandler) HandleSyncNotifications(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSyncNotifications", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleSyncNotifications indicates an expected call of HandleSyncNotifications.
func (mr *MockJobHandlerMockRecorder) HandleSyncNotifications(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSyncNotifications", reflect.TypeOf((*MockJobHandler)(nil).HandleSyncNotifications), ctx, userID)
}
