// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/view/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/view/service.go -destination=internal/core/view/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/octobud-hq/octobud/backend/internal/db"
	models "github.com/octobud-hq/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockViewService is a mock of ViewService interface.
type MockViewService struct {
	ctrl     *gomock.Controller
	recorder *MockViewServiceMockRecorder
	isgomock struct{}
}

// MockViewServiceMockRecorder is the mock recorder for MockViewService.
type MockViewServiceMockRecorder struct {
	mock *MockViewService
}

// NewMockViewService creates a new mock instance.
func NewMockViewService(ctrl *gomock.Controller) *MockViewService {
	mock := &MockViewService{ctrl: ctrl}
	mock.recorder = &MockViewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewService) EXPECT() *MockViewServiceMockRecorder {
	return m.recorder
}

// CreateView mocks base method.
func (m *MockViewService) CreateView(ctx context.Context, userID, name string, description, icon *string, isDefault *bool, queryStr string) (models.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateView", ctx, userID, name, description, icon, isDefault, queryStr)
	ret0, _ := ret[0].(models.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateView indicates an expected call of CreateView.
func (mr *MockViewServiceMockRecorder) CreateView(ctx, userID, name, description, icon, isDefault, queryStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateView", reflect.TypeOf((*MockViewService)(nil).CreateView), ctx, userID, name, description, icon, isDefault, queryStr)
}

// DeleteView mocks base method.
func (m *MockViewService) DeleteView(ctx context.Context, userID, viewID string, force bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteView", ctx, userID, viewID, force)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteView indicates an expected call of DeleteView.
func (mr *MockViewServiceMockRecorder) DeleteView(ctx, userID, viewID, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteView", reflect.TypeOf((*MockViewService)(nil).DeleteView), ctx, userID, viewID, force)
}

// GetView mocks base method.
func (m *MockViewService) GetView(ctx context.Context, userID, id string) (db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetView", ctx, userID, id)
	ret0, _ := ret[0].(db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetView indicates an expected call of GetView.
func (mr *MockViewServiceMockRecorder) GetView(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetView", reflect.TypeOf((*MockViewService)(nil).GetView), ctx, userID, id)
}

// ListViewsWithCounts mocks base method.
func (m *MockViewService) ListViewsWithCounts(ctx context.Context, userID string) ([]models.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListViewsWithCounts", ctx, userID)
	ret0, _ := ret[0].([]models.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListViewsWithCounts indicates an expected call of ListViewsWithCounts.
func (mr *MockViewServiceMockRecorder) ListViewsWithCounts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListViewsWithCounts", reflect.TypeOf((*MockViewService)(nil).ListViewsWithCounts), ctx, userID)
}

// ReorderViews mocks base method.
func (m *MockViewService) ReorderViews(ctx context.Context, userID string, viewIDs []string) ([]models.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderViews", ctx, userID, viewIDs)
	ret0, _ := ret[0].([]models.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorderViews indicates an expected call of ReorderViews.
func (mr *MockViewServiceMockRecorder) ReorderViews(ctx, userID, viewIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderViews", reflect.TypeOf((*MockViewService)(nil).ReorderViews), ctx, userID, viewIDs)
}

// UpdateView mocks base method.
func (m *MockViewService) UpdateView(ctx context.Context, userID, viewID string, name, description, icon *string, isDefault *bool, queryStr *string) (models.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateView", ctx, userID, viewID, name, description, icon, isDefault, queryStr)
	ret0, _ := ret[0].(models.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateView indicates an expected call of UpdateView.
func (mr *MockViewServiceMockRecorder) UpdateView(ctx, userID, viewID, name, description, icon, isDefault, queryStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateView", reflect.TypeOf((*MockViewService)(nil).UpdateView), ctx, userID, viewID, name, description, icon, isDefault, queryStr)
}
