// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/octobud-hq/octobud/backend/internal/github/interfaces (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=internal/github/mocks/mock_client.go -package=mocks github.com/octobud-hq/octobud/backend/internal/github/interfaces Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	types "github.com/octobud-hq/octobud/backend/internal/github/types"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchIssueComments mocks base method.
func (m *MockClient) FetchIssueComments(ctx context.Context, owner, repo string, number, perPage, page int) ([]types.IssueComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchIssueComments", ctx, owner, repo, number, perPage, page)
	ret0, _ := ret[0].([]types.IssueComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchIssueComments indicates an expected call of FetchIssueComments.
func (mr *MockClientMockRecorder) FetchIssueComments(ctx, owner, repo, number, perPage, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchIssueComments", reflect.TypeOf((*MockClient)(nil).FetchIssueComments), ctx, owner, repo, number, perPage, page)
}

// FetchNotifications mocks base method.
func (m *MockClient) FetchNotifications(ctx context.Context, since, before *time.Time, unreadOnly bool) ([]types.NotificationThread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNotifications", ctx, since, before, unreadOnly)
	ret0, _ := ret[0].([]types.NotificationThread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNotifications indicates an expected call of FetchNotifications.
func (mr *MockClientMockRecorder) FetchNotifications(ctx, since, before, unreadOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNotifications", reflect.TypeOf((*MockClient)(nil).FetchNotifications), ctx, since, before, unreadOnly)
}

// FetchPullRequestReviews mocks base method.
func (m *MockClient) FetchPullRequestReviews(ctx context.Context, owner, repo string, number, perPage, page int) ([]types.PullRequestReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPullRequestReviews", ctx, owner, repo, number, perPage, page)
	ret0, _ := ret[0].([]types.PullRequestReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPullRequestReviews indicates an expected call of FetchPullRequestReviews.
func (mr *MockClientMockRecorder) FetchPullRequestReviews(ctx, owner, repo, number, perPage, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPullRequestReviews", reflect.TypeOf((*MockClient)(nil).FetchPullRequestReviews), ctx, owner, repo, number, perPage, page)
}

// FetchSubjectRaw mocks base method.
func (m *MockClient) FetchSubjectRaw(ctx context.Context, subjectURL string) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSubjectRaw", ctx, subjectURL)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSubjectRaw indicates an expected call of FetchSubjectRaw.
func (mr *MockClientMockRecorder) FetchSubjectRaw(ctx, subjectURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSubjectRaw", reflect.TypeOf((*MockClient)(nil).FetchSubjectRaw), ctx, subjectURL)
}

// FetchTimeline mocks base method.
func (m *MockClient) FetchTimeline(ctx context.Context, owner, repo string, number, perPage, page int) ([]types.TimelineEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTimeline", ctx, owner, repo, number, perPage, page)
	ret0, _ := ret[0].([]types.TimelineEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTimeline indicates an expected call of FetchTimeline.
func (mr *MockClientMockRecorder) FetchTimeline(ctx, owner, repo, number, perPage, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTimeline", reflect.TypeOf((*MockClient)(nil).FetchTimeline), ctx, owner, repo, number, perPage, page)
}

// SetToken mocks base method.
func (m *MockClient) SetToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetToken indicates an expected call of SetToken.
func (mr *MockClientMockRecorder) SetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockClient)(nil).SetToken), ctx, token)
}
